# Generated by Django 6.0.3 on 2026-08-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0002_publicconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenants',
            field=models.ManyToManyField(blank=True, help_text='The schools/tenants this user is authorized to access.', related_name='users', to='tenants.client'),
        ),
    ]
