# Generated by Django 6.0.3 on 2026-05-23 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0016_user_session_timeout"),
        ("student_settings", "0015_admissionworkflowconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="academic_faculty_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dean",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dean_of_faculties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="academic_faculty_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Faculties",
                "db_table": "faculties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="academic_department_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="head_of_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="academic_department_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="departments",
                        to="programmes.faculty",
                    ),
                ),
            ],
            options={
                "db_table": "departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("certificate", "Certificate"),
                            ("diploma", "Diploma"),
                            ("degree", "Bachelor's Degree"),
                            ("masters", "Master's Degree"),
                            ("phd", "PhD / Doctorate"),
                            ("short_course", "Short Course / Professional"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Numeric duration, e.g. 3 (years)"
                    ),
                ),
                (
                    "duration_type",
                    models.CharField(
                        choices=[
                            ("years", "Years"),
                            ("months", "Months"),
                            ("semesters", "Semesters"),
                            ("weeks", "Weeks"),
                        ],
                        default="years",
                        max_length=10,
                    ),
                ),
                (
                    "total_credit_units",
                    models.PositiveIntegerField(
                        default=0, help_text="Minimum credit units required to graduate"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "minimum_entry_requirements",
                    models.TextField(
                        blank=True, help_text="E.g. KCSE grade C+ or equivalent"
                    ),
                ),
                (
                    "has_specialization",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this programme has named tracks/specializations",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programmes",
                        to="programmes.department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "programmes",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="programmes.programme",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "programme_specializations",
                "ordering": ["name"],
                "unique_together": {("programme", "code")},
            },
        ),
        migrations.CreateModel(
            name="ProgrammeUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "credit_units",
                    models.DecimalField(
                        decimal_places=1,
                        default=3.0,
                        help_text="Credit hours / units for this course",
                        max_digits=4,
                    ),
                ),
                (
                    "year_of_study",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Year in which this unit is normally taught (1, 2, 3…)",
                    ),
                ),
                (
                    "semester_offered",
                    models.CharField(
                        choices=[
                            ("1", "Semester 1"),
                            ("2", "Semester 2"),
                            ("both", "Both Semesters"),
                            ("any", "Any Semester"),
                        ],
                        default="1",
                        max_length=10,
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("core", "Core / Compulsory"),
                            ("elective", "Elective"),
                            ("prerequisite", "Prerequisite"),
                            ("audit", "Audit Only"),
                        ],
                        default="core",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Units that must be passed before taking this unit",
                        related_name="required_before",
                        to="programmes.programmeunit",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="programmes.programme",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link only if this unit belongs to a specific specialization",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="units",
                        to="programmes.specialization",
                    ),
                ),
            ],
            options={
                "db_table": "programme_units",
                "ordering": ["year_of_study", "code"],
            },
        ),
        migrations.CreateModel(
            name="ProgrammeEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "registration_number",
                    models.CharField(
                        help_text="Institution-issued registration/student number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("year_of_study", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deferred", "Deferred"),
                            ("completed", "Completed / Graduated"),
                            ("withdrawn", "Withdrawn"),
                            ("suspended", "Suspended"),
                            ("transferred", "Transferred"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("enrollment_date", models.DateField()),
                ("expected_graduation", models.DateField(blank=True, null=True)),
                ("actual_graduation", models.DateField(blank=True, null=True)),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cumulative GPA — computed by the grading module",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_programme_enrollments",
                        to="student_settings.term",
                    ),
                ),
                (
                    "intake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programme_enrollments",
                        to="student_settings.intake",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="programmes.programme",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programme_enrollments",
                        to="accounts.student",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments",
                        to="programmes.specialization",
                    ),
                ),
            ],
            options={
                "db_table": "programme_enrollments",
                "ordering": ["-enrollment_date"],
            },
        ),
        migrations.CreateModel(
            name="UnitOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("room", models.CharField(blank=True, max_length=100)),
                ("max_students", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_offerings",
                        to="student_settings.intake",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unit_offerings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        help_text="Term used as semester for tertiary mode",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_offerings",
                        to="student_settings.term",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="programmes.programmeunit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "unit_offerings",
                "ordering": ["intake", "unit__year_of_study", "unit__code"],
                "unique_together": {("unit", "intake", "semester")},
            },
        ),
        migrations.CreateModel(
            name="UnitRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("dropped", "Dropped"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("incomplete", "Incomplete"),
                            ("audit", "Auditing"),
                        ],
                        default="registered",
                        max_length=15,
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "grade_points",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="programmes.unitoffering",
                    ),
                ),
                (
                    "programme_enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_registrations",
                        to="programmes.programmeenrollment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "unit_registrations",
                "ordering": ["-offering__semester__start_date"],
                "unique_together": {("programme_enrollment", "offering")},
            },
        ),
    ]
