# Generated by Django 6.0.3 on 2026-07-27 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Institution Name')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Abbreviation')),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('institution_type', models.CharField(choices=[('lower_primary', 'Lower Primary'), ('upper_primary', 'Upper Primary'), ('primary', 'Primary School'), ('junior_secondary', 'Junior Secondary'), ('senior_secondary', 'Senior Secondary'), ('secondary', 'Secondary School (Junior & Senior)'), ('mixed', 'Mixed (Primary & Secondary)'), ('tertiary', 'Tertiary / College'), ('university', 'University'), ('tvet', 'TVET Institution')], default='secondary', max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='Registration / License No.')),
                ('established_date', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100, verbose_name='County / State')),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('primary_color', models.CharField(blank=True, default='#4f46e5', max_length=7)),
                ('secondary_color', models.CharField(blank=True, default='#f59e0b', max_length=7)),
                ('portal_url', models.URLField(blank=True, help_text='Login URL sent in admission emails', verbose_name='Student/Parent Portal URL')),
                ('principal_name', models.CharField(blank=True, help_text='Appears on the signature block of generated letters', max_length=150, verbose_name='Principal / Head Name')),
                ('principal_title', models.CharField(blank=True, default='PRINCIPAL', help_text='e.g. PRINCIPAL, HEAD TEACHER, DIRECTOR', max_length=100, verbose_name='Principal Title')),
                ('signature_image', models.ImageField(blank=True, help_text='Drawn or uploaded signature — appears above the principal name on letters', null=True, upload_to='institution/signatures/')),
                ('stamp_image', models.ImageField(blank=True, help_text='Official school stamp / seal — overlaid on the signature block', null=True, upload_to='institution/stamps/')),
            ],
            options={
                'verbose_name': 'Institution Profile',
                'verbose_name_plural': 'Institution Profile',
            },
        ),
        migrations.CreateModel(
            name='NewsAndEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('title_es', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('summary', models.TextField(blank=True, max_length=200, null=True)),
                ('summary_en', models.TextField(blank=True, max_length=200, null=True)),
                ('summary_fr', models.TextField(blank=True, max_length=200, null=True)),
                ('summary_es', models.TextField(blank=True, max_length=200, null=True)),
                ('summary_ru', models.TextField(blank=True, max_length=200, null=True)),
                ('posted_as', models.CharField(choices=[('News', 'News'), ('Event', 'Event')], max_length=10)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200, unique=True)),
                ('is_current_session', models.BooleanField(blank=True, default=False, null=True)),
                ('next_session_begins', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=10)),
                ('is_current_semester', models.BooleanField(blank=True, default=False, null=True)),
                ('next_semester_begins', models.DateField(blank=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON'), ('secret', 'Secret')], default='string', max_length=10)),
                ('group', models.CharField(choices=[('payments', 'Payments & M-Pesa'), ('timetable', 'Timetable'), ('notifications', 'Notifications'), ('grading', 'Grading & Reports'), ('security', 'Security'), ('admissions', 'Admissions'), ('general', 'General')], default='general', max_length=20)),
                ('label', models.CharField(help_text='Human-readable label shown in the UI', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Help text shown under the field')),
                ('is_editable', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_system_config',
                'ordering': ['group', 'display_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('OTHER', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('module', models.CharField(blank=True, help_text='App label', max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, help_text='Diff of old → new values for UPDATE actions', null=True)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_audit__user_id_1daed5_idx'), models.Index(fields=['action', '-timestamp'], name='core_audit__action_a453b1_idx'), models.Index(fields=['module', 'model_name'], name='core_audit__module_18365d_idx')],
            },
        ),
    ]
