# Generated by Django 6.0.3 on 2026-04-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_newsandevents_summary_es_newsandevents_summary_fr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Institution Name"),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Abbreviation"
                    ),
                ),
                ("motto", models.CharField(blank=True, max_length=255)),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary School"),
                            ("secondary", "Secondary School"),
                            ("mixed", "Mixed (Primary & Secondary)"),
                            ("tertiary", "Tertiary / College"),
                            ("university", "University"),
                            ("tvet", "TVET Institution"),
                        ],
                        default="secondary",
                        max_length=20,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Registration / License No.",
                    ),
                ),
                ("established_date", models.DateField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="institution/"),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("website", models.URLField(blank=True)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "county",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="County / State"
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="Kenya", max_length=100)),
                (
                    "primary_color",
                    models.CharField(blank=True, default="#4f46e5", max_length=7),
                ),
                (
                    "secondary_color",
                    models.CharField(blank=True, default="#f59e0b", max_length=7),
                ),
                (
                    "portal_url",
                    models.URLField(
                        blank=True,
                        help_text="Login URL sent in admission emails",
                        verbose_name="Student/Parent Portal URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institution Profile",
                "verbose_name_plural": "Institution Profile",
            },
        ),
    ]
