# Generated by Django 6.0.3 on 2026-04-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_systemconfiguration_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutionprofile",
            name="institution_type",
            field=models.CharField(
                choices=[
                    ("lower_primary", "Lower Primary"),
                    ("upper_primary", "Upper Primary"),
                    ("primary", "Primary School"),
                    ("secondary", "Secondary School"),
                    ("mixed", "Mixed (Primary & Secondary)"),
                    ("tertiary", "Tertiary / College"),
                    ("university", "University"),
                    ("tvet", "TVET Institution"),
                ],
                default="secondary",
                max_length=20,
            ),
        ),
    ]
