# Generated by Django 6.0.3 on 2026-04-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_institutionprofile_institution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionprofile',
            name='institution_type',
            field=models.CharField(choices=[('lower_primary', 'Lower Primary'), ('upper_primary', 'Upper Primary'), ('primary', 'Primary School'), ('junior_secondary', 'Junior Secondary'), ('senior_secondary', 'Senior Secondary'), ('secondary', 'Secondary School (Junior & Senior)'), ('mixed', 'Mixed (Primary & Secondary)'), ('tertiary', 'Tertiary / College'), ('university', 'University'), ('tvet', 'TVET Institution')], default='secondary', max_length=20),
        ),
    ]
