# Generated by Django 6.0.3 on 2026-04-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_institutionprofile_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionprofile',
            name='principal_name',
            field=models.CharField(blank=True, help_text='Appears on the signature block of generated letters', max_length=150, verbose_name='Principal / Head Name'),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='principal_title',
            field=models.CharField(blank=True, default='PRINCIPAL', help_text='e.g. PRINCIPAL, HEAD TEACHER, DIRECTOR', max_length=100, verbose_name='Principal Title'),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Drawn or uploaded signature — appears above the principal name on letters', null=True, upload_to='institution/signatures/'),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='stamp_image',
            field=models.ImageField(blank=True, help_text='Official school stamp / seal — overlaid on the signature block', null=True, upload_to='institution/stamps/'),
        ),
    ]
