# Generated by Django 6.0.1 on 2026-01-25 22:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
        ('workforce', '0005_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificates_verified', models.BooleanField(default=False)),
                ('teaching_license_verified', models.BooleanField(default=False)),
                ('references_checked', models.BooleanField(default=False)),
                ('criminal_clearance_verified', models.BooleanField(default=False)),
                ('medical_clearance_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checklist', to='recruitment.jobapplication')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruitment_compliance_checklist',
            },
        ),
        migrations.CreateModel(
            name='OnboardingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_created', models.BooleanField(default=False)),
                ('system_access_granted', models.BooleanField(default=False)),
                ('department_assigned', models.BooleanField(default=False)),
                ('timetable_assigned', models.BooleanField(default=False)),
                ('documents_submitted', models.BooleanField(default=False)),
                ('progress_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_process', to='recruitment.jobapplication')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_process_record', to='workforce.employee')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruitment_onboarding_process',
            },
        ),
        migrations.CreateModel(
            name='ProbationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('review_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('confirmed', 'Confirmed'), ('extended', 'Extended'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('performance_rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probation_reviews', to='workforce.employee')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruitment_probation_review',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='SelectionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('selected', 'Selected'), ('waitlisted', 'Waitlisted'), ('not_selected', 'Not Selected')], max_length=20)),
                ('hr_approved', models.BooleanField(default=False)),
                ('hr_approval_date', models.DateTimeField(blank=True, null=True)),
                ('principal_approved', models.BooleanField(default=False)),
                ('principal_approval_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selection_decision', to='recruitment.jobapplication')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('hr_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections_hr_approved', to='workforce.employee')),
                ('principal_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections_principal_approved', to='workforce.employee')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruitment_selection_decision',
            },
        ),
    ]
