# Generated by Django 6.0.1 on 2026-01-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_code_alter_course_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
    ]
