# Generated by Django 6.0.1 on 2026-01-28 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Unique account code (e.g. 1000)', max_length=20, unique=True)),
                ('type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=20)),
                ('sub_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('ACCOUNTS_RECEIVABLE', 'Accounts Receivable'), ('PREPAYMENTS', 'Prepayments'), ('INVENTORY', 'Inventory'), ('FIXED_ASSET', 'Fixed Asset'), ('ACCUMULATED_DEPRECIATION', 'Accumulated Depreciation'), ('ACCOUNTS_PAYABLE', 'Accounts Payable'), ('ACCRUED_EXPENSES', 'Accrued Expenses'), ('DEFERRED_REVENUE', 'Deferred Revenue'), ('TAX_PAYABLE', 'Tax Payable'), ('LONG_TERM_LIABILITY', 'Long Term Liability'), ('CAPITAL', 'Capital'), ('RETAINED_EARNINGS', 'Retained Earnings'), ('CURRENT_YEAR_SURPLUS', 'Current Year Surplus'), ('SERVICE_INCOME', 'Service Income'), ('GRANTS_DONATIONS', 'Grants & Donations'), ('OTHER_INCOME', 'Other Income'), ('SALARIES_WAGES', 'Salaries & Wages'), ('UTILITIES', 'Utilities'), ('TEACHING_EXPENSES', 'Teaching Expenses'), ('ADMIN_EXPENSES', 'Admin Expenses'), ('MAINTENANCE', 'Maintenance'), ('DEPRECIATION', 'Depreciation')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent account for hierarchy. Postings allowed only to leaf accounts.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='finance.account')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['code'],
            },
        ),
    ]
