# Generated by Django 6.0.1 on 2026-01-29 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2024, Q1 2025', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False, help_text='If closed, no further transactions can be posted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Cashbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Main Office Cash, Petty Cash', max_length=100)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('low_cash_threshold', models.DecimalField(decimal_places=2, default=0.0, help_text='Alert when balance drops below this amount.', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='The GL Asset Account linked to this cashbook.', limit_choices_to={'type': 'ASSET'}, on_delete=django.db.models.deletion.RESTRICT, to='finance.account')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year_start_month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1)),
                ('financial_year_start_day', models.IntegerField(default=1)),
                ('currency_code', models.CharField(default='KES', max_length=10)),
                ('currency_symbol', models.CharField(default='KSh', max_length=5)),
                ('tax_id_label', models.CharField(default='KRA PIN', help_text='Label for Tax ID field on invoices', max_length=50)),
                ('vat_enabled', models.BooleanField(default=False)),
                ('budgeting_enabled', models.BooleanField(default=True)),
                ('receipt_prefix', models.CharField(default='RCPT', max_length=10)),
                ('receipt_footer_message', models.TextField(blank=True, default='Thank you for your business.')),
                ('receipt_show_balance', models.BooleanField(default=True)),
                ('receipt_show_voteheads', models.BooleanField(default=True, help_text='Breakdown receipts per invoice vote head')),
                ('voucher_attachments_required', models.BooleanField(default=False)),
                ('imprest_max_amount', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12)),
                ('imprest_surrender_days', models.IntegerField(default=7, help_text='Days to surrender imprest after issuance')),
                ('auto_billing_enabled', models.BooleanField(default=False)),
                ('billing_frequency', models.CharField(choices=[('YEARLY', 'Yearly'), ('TERMLY', 'Termly'), ('MONTHLY', 'Monthly')], default='TERMLY', max_length=20)),
                ('default_billing_days', models.IntegerField(default=14, help_text='Default due days for auto-generated invoices')),
                ('low_cash_alert_enabled', models.BooleanField(default=True)),
                ('overdue_invoice_alert_enabled', models.BooleanField(default=True)),
                ('voucher_approval_levels', models.IntegerField(default=1, help_text='Number of approvals required for vouchers')),
                ('imprest_approval_levels', models.IntegerField(default=1, help_text='Number of approvals required for imprest')),
                ('default_bank_account', models.ForeignKey(blank=True, limit_choices_to={'sub_type': 'BANK'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_bank', to='finance.account')),
                ('default_payable_account', models.ForeignKey(blank=True, limit_choices_to={'sub_type': 'ACCOUNTS_PAYABLE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_payable', to='finance.account')),
                ('default_receivable_account', models.ForeignKey(blank=True, limit_choices_to={'sub_type': 'ACCOUNTS_RECEIVABLE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_receivable', to='finance.account')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_for_payment', models.BooleanField(default=True, verbose_name='Can Make Payments')),
                ('is_for_receipt', models.BooleanField(default=True, verbose_name='Can Receive Payments')),
                ('is_sponsorship_clearing', models.BooleanField(default=False, help_text='Used for clearing sponsorship allocations')),
                ('is_application_fee', models.BooleanField(default=False, help_text='Used for application fee payments')),
                ('account', models.ForeignKey(blank=True, help_text='The GL Account where transactions for this method are posted.', limit_choices_to={'type__in': ['ASSET', 'LIABILITY']}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='payment_methods', to='finance.account')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage (e.g., 16.00 for 16%)', max_digits=5)),
                ('type', models.CharField(choices=[('SALES', 'Sales Tax (Collected on Income)'), ('PURCHASE', 'Purchase Tax (Paid on Expenses)'), ('BOTH', 'Both')], default='BOTH', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='Liability account to post tax to (e.g. VAT Payable)', limit_choices_to={'type': 'LIABILITY'}, on_delete=django.db.models.deletion.RESTRICT, related_name='taxes', to='finance.account')),
            ],
        ),
    ]
