# Generated by Django 6.0.1 on 2026-01-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_fiscalperiod_cashbook_financesettings_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_student_related',
            field=models.BooleanField(default=False, help_text='Check if this account is used for student transactions (e.g. Fees, Caution Money)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='sub_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('ACCOUNTS_RECEIVABLE', 'Accounts Receivable'), ('PREPAYMENTS', 'Prepayments'), ('INVENTORY', 'Inventory'), ('FIXED_ASSET', 'Fixed Asset'), ('ACCUMULATED_DEPRECIATION', 'Accumulated Depreciation'), ('ACCOUNTS_PAYABLE', 'Accounts Payable'), ('ACCRUED_EXPENSES', 'Accrued Expenses'), ('DEFERRED_REVENUE', 'Deferred Revenue'), ('TAX_PAYABLE', 'Tax Payable'), ('LONG_TERM_LIABILITY', 'Long Term Liability'), ('REFUNDABLE_DEPOSIT', 'Refundable Deposit'), ('CAPITAL', 'Capital'), ('RETAINED_EARNINGS', 'Retained Earnings'), ('CURRENT_YEAR_SURPLUS', 'Current Year Surplus'), ('SERVICE_INCOME', 'Service Income'), ('GRANTS_DONATIONS', 'Grants & Donations'), ('OTHER_INCOME', 'Other Income'), ('SALARIES_WAGES', 'Salaries & Wages'), ('UTILITIES', 'Utilities'), ('TEACHING_EXPENSES', 'Teaching Expenses'), ('ADMIN_EXPENSES', 'Admin Expenses'), ('MAINTENANCE', 'Maintenance'), ('DEPRECIATION', 'Depreciation')], max_length=50),
        ),
    ]
