# Generated by Django 6.0.1 on 2026-01-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_account_is_student_related_alter_account_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='is_opening_balance_posted',
            field=models.BooleanField(default=False, help_text='System flag: True if opening balance journal created'),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='opening_balance_date',
            field=models.DateField(blank=True, help_text='Date of opening balance', null=True),
        ),
    ]
