# Generated by Django 6.0.1 on 2026-01-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_cashbook_is_opening_balance_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default for Payment Vouchers'),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='voucher_prefix',
            field=models.CharField(default='PV', help_text='Prefix for vouchers from this cashbook (e.g. PV-)', max_length=10),
        ),
    ]
