# Generated by Django 6.0.1 on 2026-01-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_cashbook_is_active_cashbook_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(blank=True, help_text='Bank Account Number, Paybill, or Till Number', max_length=50, null=True),
        ),
    ]
