# Generated by Django 6.0.1 on 2026-01-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_paymentmethod_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(default='Payment Method', help_text='e.g. M-Pesa, Equity Bank', max_length=50),
        ),
    ]
