# Generated by Django 6.0.1 on 2026-02-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_journalentry_journalline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalline',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='account',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='JournalLine',
        ),
    ]
