# Generated by Django 6.0.1 on 2026-02-04 08:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_student_status'),
        ('fees', '0002_feeinvoice_feeinvoiceitem'),
        ('finance', '0009_remove_journalline_entry_remove_journalline_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financesettings',
            options={'verbose_name': 'Finance Settings', 'verbose_name_plural': 'Finance Settings'},
        ),
        migrations.AddField(
            model_name='financesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financesettings',
            name='default_prepayment_account',
            field=models.ForeignKey(blank=True, help_text='Account for student prepayments/unallocated credits', limit_choices_to={'account_type': 'LIABILITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_prepayment', to='finance.account'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('receipt_type', models.CharField(choices=[('STUDENT_FEE', 'Student Fee Payment'), ('STUDENT_NON_FEE', 'Student Non-Fee Payment'), ('SPONSORSHIP', 'Sponsorship Payment'), ('CUSTOMER', 'Customer Payment'), ('GENERAL', 'General Receipt')], default='STUDENT_FEE', max_length=20)),
                ('amount_received', models.DecimalField(decimal_places=2, help_text='Total amount received from payer', max_digits=12)),
                ('amount_allocated', models.DecimalField(decimal_places=2, default=0, help_text='Amount allocated to invoices (updated by allocation service)', max_digits=12)),
                ('received_date', models.DateField()),
                ('reference', models.CharField(blank=True, help_text='External reference: Cheque #, M-Pesa code, Bank transfer ref, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_posted', models.BooleanField(default=False, help_text='True when allocations have been created. Receipt becomes immutable.')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='finance.paymentmethod')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, help_text='Required for STUDENT_FEE and STUDENT_NON_FEE types', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-received_date', '-receipt_number'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount allocated to this invoice item', max_digits=12)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_allocations', to='fees.feeinvoice')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_allocations', to='fees.feeinvoiceitem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.receipt')),
            ],
            options={
                'verbose_name': 'Receipt Allocation',
                'verbose_name_plural': 'Receipt Allocations',
                'ordering': ['allocated_at', 'invoice__date_issued'],
            },
        ),
        migrations.CreateModel(
            name='StudentPrepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Original prepayment amount', max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Remaining prepayment balance (decreases as used)', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_fully_used', models.BooleanField(default=False, help_text='True when balance reaches zero')),
                ('receipt', models.ForeignKey(help_text='Original receipt that created this prepayment', on_delete=django.db.models.deletion.PROTECT, related_name='prepayment_records', to='finance.receipt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepayments', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Student Prepayment',
                'verbose_name_plural': 'Student Prepayments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['student', 'received_date'], name='finance_rec_student_7f5829_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='finance_rec_receipt_e3529a_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['is_posted'], name='finance_rec_is_post_4f2edf_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptallocation',
            index=models.Index(fields=['receipt', 'invoice'], name='finance_rec_receipt_c370dc_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptallocation',
            index=models.Index(fields=['invoice_item'], name='finance_rec_invoice_008493_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='receiptallocation',
            unique_together={('receipt', 'invoice_item')},
        ),
        migrations.AddIndex(
            model_name='studentprepayment',
            index=models.Index(fields=['student', 'is_fully_used'], name='finance_stu_student_11d35e_idx'),
        ),
    ]
