# Generated by Django 6.0.1 on 2026-02-04 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_financesettings_options_and_more'),
        ('student_settings', '0008_enrollment_reporting_reason_enrollment_stay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for student fee payments', null=True, on_delete=django.db.models.deletion.PROTECT, to='student_settings.academicyear'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='allocation_rule',
            field=models.TextField(blank=True, help_text='Rule for allocating sponsorship amount to students', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='description',
            field=models.TextField(blank=True, help_text='Description for non-fee items or general receipts', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='fee_category',
            field=models.CharField(blank=True, help_text='Fee category name (e.g., Tuition Fees, Boarding Fees)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='income_account',
            field=models.ForeignKey(blank=True, help_text='Income account for general receipts (e.g., Donations, Rental Income)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_income', to='finance.account'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='non_fee_category',
            field=models.CharField(blank=True, help_text='Non-fee item category (e.g., School Uniform, Educational Trip)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payer_name',
            field=models.CharField(default='Student.username', help_text='Name of the person/entity making the payment', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='print_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this receipt has been printed'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='reversal_reason',
            field=models.TextField(blank=True, help_text='Reason for reversing this receipt (if status is REVERSED)', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='sponsorship_type',
            field=models.CharField(blank=True, help_text='Type of sponsorship (e.g., Full Scholarship, Partial Scholarship)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PRINTED', 'Printed'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='receipt',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Academic term for student fee payments', null=True, on_delete=django.db.models.deletion.PROTECT, to='student_settings.term'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_type',
            field=models.CharField(choices=[('STUDENT_FEE', 'Student Fee'), ('STUDENT_NON_FEE', 'Student Non-Fee'), ('SPONSOR', 'Sponsor'), ('GENERAL', 'General')], default='STUDENT_FEE', max_length=20),
        ),
    ]
