# Generated by Django 6.0.1 on 2026-02-04 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_receipt_academic_year_receipt_allocation_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financesettings',
            name='default_prepayment_account',
            field=models.ForeignKey(blank=True, help_text='Account for student prepayments/unallocated credits', limit_choices_to={'type': 'LIABILITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_prepayment', to='finance.account'),
        ),
    ]
