# Generated by Django 6.0.1 on 2026-02-04 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feeinvoice_feeinvoiceitem'),
        ('finance', '0012_alter_financesettings_default_prepayment_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='fees.feeinvoice'),
        ),
        migrations.AlterField(
            model_name='receiptallocation',
            name='invoice_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='fees.feeinvoiceitem'),
        ),
    ]
