# Generated by Django 6.0.2 on 2026-03-12 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0013_alter_receiptallocation_invoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financesettings",
            name="default_sundry_debtors_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Account for sundry/other debtors (non-student receivables)",
                limit_choices_to={"type": "ASSET"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settings_sundry_debtors",
                to="finance.account",
            ),
        ),
    ]
