# Generated by Django 6.0.3 on 2026-04-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_financesettings_default_sundry_debtors_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='available_in_payroll',
            field=models.BooleanField(default=False, help_text='Check if this account should be available for payroll account linkage'),
        ),
    ]
