# Generated by Django 6.0.3 on 2026-04-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_account_available_in_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='billing_mode',
            field=models.CharField(choices=[('STRUCTURE', 'Per-Grade Fee Structure'), ('TEMPLATE', 'Grade-Band Fee Template'), ('AUTO', 'Auto (Template first, fallback to Structure)')], default='STRUCTURE', help_text='Which billing pipeline to use when auto-generating invoices', max_length=20),
        ),
    ]
