# Generated by Django 6.0.3 on 2026-04-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0016_add_billing_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="financesettings",
            name="receipt_coat_of_arms",
            field=models.ImageField(
                blank=True,
                help_text="Coat of arms or government seal",
                null=True,
                upload_to="receipt_branding/",
            ),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="receipt_color_primary",
            field=models.CharField(
                default="#1a56db", help_text="Primary accent color (hex)", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="receipt_color_secondary",
            field=models.CharField(
                default="#374151",
                help_text="Secondary color for headers (hex)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="receipt_copies",
            field=models.IntegerField(
                choices=[
                    (1, "Original Only"),
                    (2, "Original + Duplicate"),
                    (3, "Original + Duplicate + Office Copy"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="receipt_format",
            field=models.CharField(
                choices=[
                    ("STANDARD_A4", "Standard A4 (Full Page)"),
                    ("COMPACT_A4", "Compact A4 (Half Page)"),
                    ("THERMAL_80MM", "POS Thermal 80mm"),
                    ("THERMAL_58MM", "POS Thermal 58mm"),
                    ("DUPLICATE_BOOK", "Duplicate Book Style"),
                ],
                default="THERMAL_80MM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="receipt_header_style",
            field=models.CharField(
                choices=[
                    ("LOGO_ONLY", "Logo Only"),
                    ("COAT_ONLY", "Coat of Arms Only"),
                    ("BOTH_SIDE", "Logo Left, Coat of Arms Right"),
                    ("COAT_LEFT_LOGO_RIGHT", "Coat of Arms Left, Logo Right"),
                    ("BOTH_CENTER", "Both Centered (Stacked)"),
                ],
                default="LOGO_ONLY",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="receipt_institution_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Address line on receipt",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="receipt_institution_email",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="receipt_institution_motto",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="receipt_institution_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Institution name on receipt header",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="receipt_institution_phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="receipt_logo",
            field=models.ImageField(
                blank=True,
                help_text="School/Institution logo",
                null=True,
                upload_to="receipt_branding/",
            ),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="receipt_paper_size",
            field=models.CharField(
                choices=[("A4", "A4"), ("LETTER", "Letter"), ("A5", "A5")],
                default="A4",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="receipt_show_qr_code",
            field=models.BooleanField(
                default=True, help_text="Show QR code for verification"
            ),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="receipt_show_student_photo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="receipt_signature_enabled",
            field=models.BooleanField(
                default=True, help_text="Show signature line on receipt"
            ),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="receipt_watermark_enabled",
            field=models.BooleanField(
                default=False, help_text="Light coat of arms watermark on A4 receipts"
            ),
        ),
    ]
