# Generated by Django 6.0.3 on 2026-04-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0017_financesettings_receipt_coat_of_arms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financesettings",
            name="receipt_format",
            field=models.CharField(
                choices=[
                    ("STANDARD_A4", "Standard A4 (Full Page)"),
                    ("COMPACT_A4", "Compact A4 (Half Page)"),
                    ("A5_RECEIPT", "A5 Receipt"),
                    ("THERMAL_80MM", "POS Thermal 80mm"),
                    ("THERMAL_58MM", "POS Thermal 58mm"),
                    ("DUPLICATE_BOOK", "Duplicate Book Style"),
                ],
                default="THERMAL_80MM",
                max_length=20,
            ),
        ),
    ]
