# Generated by Django 6.0.3 on 2026-05-25 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0018_alter_financesettings_receipt_format"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier or code for the sponsor",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sponsorship",
                "verbose_name_plural": "Sponsorships",
            },
        ),
        migrations.AddField(
            model_name="receipt",
            name="parent_receipt",
            field=models.ForeignKey(
                blank=True,
                help_text="Sponsor receipt that this student payment was allocated from",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_allocations",
                to="finance.receipt",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="sponsorship",
            field=models.ForeignKey(
                blank=True,
                help_text="Required for SPONSOR receipt type",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="finance.sponsorship",
            ),
        ),
        migrations.CreateModel(
            name="SponsorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clearing_account",
                    models.ForeignKey(
                        help_text="Liability account used in clearing sponsorship receipts during allocations",
                        limit_choices_to={"type": "LIABILITY"},
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sponsor_types",
                        to="finance.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sponsor Type",
                "verbose_name_plural": "Sponsor Types",
            },
        ),
        migrations.AddField(
            model_name="sponsorship",
            name="sponsor_type",
            field=models.ForeignKey(
                help_text="The category of this sponsor",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sponsorships",
                to="finance.sponsortype",
            ),
        ),
    ]
