# Generated by Django 6.0.3 on 2026-07-27 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programmes', '0001_initial'),
        ('student_management', '0001_initial'),
        ('student_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeenrollment',
            name='current_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_programme_enrollments', to='student_settings.term'),
        ),
        migrations.AddField(
            model_name='programmeenrollment',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programme_enrollments', to='student_settings.intake'),
        ),
        migrations.AddField(
            model_name='programmeenrollment',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='programmes.programme'),
        ),
        migrations.AddField(
            model_name='programmeenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_enrollments', to='student_management.student'),
        ),
        migrations.AddField(
            model_name='programmeenrollment',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programmeunit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programmeunit',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Units that must be passed before taking this unit', related_name='required_before', to='programmes.programmeunit'),
        ),
        migrations.AddField(
            model_name='programmeunit',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='programmes.programme'),
        ),
        migrations.AddField(
            model_name='programmeunit',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialization',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialization',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='programmes.programme'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programmeunit',
            name='specialization',
            field=models.ForeignKey(blank=True, help_text='Link only if this unit belongs to a specific specialization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='programmes.specialization'),
        ),
        migrations.AddField(
            model_name='programmeenrollment',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='programmes.specialization'),
        ),
        migrations.AddField(
            model_name='unitoffering',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitoffering',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_offerings', to='student_settings.intake'),
        ),
        migrations.AddField(
            model_name='unitoffering',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_offerings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitoffering',
            name='semester',
            field=models.ForeignKey(help_text='Term used as semester for tertiary mode', on_delete=django.db.models.deletion.CASCADE, related_name='unit_offerings', to='student_settings.term'),
        ),
        migrations.AddField(
            model_name='unitoffering',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='programmes.programmeunit'),
        ),
        migrations.AddField(
            model_name='unitoffering',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitregistration',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitregistration',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='programmes.unitoffering'),
        ),
        migrations.AddField(
            model_name='unitregistration',
            name='programme_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_registrations', to='programmes.programmeenrollment'),
        ),
        migrations.AddField(
            model_name='unitregistration',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='specialization',
            unique_together={('programme', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='unitoffering',
            unique_together={('unit', 'intake', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='unitregistration',
            unique_together={('programme_enrollment', 'offering')},
        ),
    ]
