# Generated by Django 6.0.3 on 2026-07-27 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0002_initial'),
        ('finance', '0001_initial'),
        ('student_management', '0001_initial'),
        ('student_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for student fee payments', null=True, on_delete=django.db.models.deletion.PROTECT, to='student_settings.academicyear'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='income_account',
            field=models.ForeignKey(blank=True, help_text='Income account for general receipts (e.g., Donations, Rental Income)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_income', to='finance.account'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='parent_receipt',
            field=models.ForeignKey(blank=True, help_text='Sponsor receipt that this student payment was allocated from', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_allocations', to='finance.receipt'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='finance.paymentmethod'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Required for STUDENT_FEE and STUDENT_NON_FEE types', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='student_management.student'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Academic term for student fee payments', null=True, on_delete=django.db.models.deletion.PROTECT, to='student_settings.term'),
        ),
        migrations.AddField(
            model_name='receiptallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='fees.feeinvoice'),
        ),
        migrations.AddField(
            model_name='receiptallocation',
            name='invoice_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='fees.feeinvoiceitem'),
        ),
        migrations.AddField(
            model_name='receiptallocation',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.receipt'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='sponsorship',
            field=models.ForeignKey(blank=True, help_text='Required for SPONSOR receipt type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='finance.sponsorship'),
        ),
        migrations.AddField(
            model_name='sponsortype',
            name='clearing_account',
            field=models.ForeignKey(help_text='Liability account used in clearing sponsorship receipts during allocations', limit_choices_to={'type': 'LIABILITY'}, on_delete=django.db.models.deletion.RESTRICT, related_name='sponsor_types', to='finance.account'),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='sponsor_type',
            field=models.ForeignKey(help_text='The category of this sponsor', on_delete=django.db.models.deletion.PROTECT, related_name='sponsorships', to='finance.sponsortype'),
        ),
        migrations.AddField(
            model_name='studentprepayment',
            name='receipt',
            field=models.ForeignKey(help_text='Original receipt that created this prepayment', on_delete=django.db.models.deletion.PROTECT, related_name='prepayment_records', to='finance.receipt'),
        ),
        migrations.AddField(
            model_name='studentprepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepayments', to='student_management.student'),
        ),
        migrations.AddField(
            model_name='tax',
            name='account',
            field=models.ForeignKey(help_text='Liability account to post tax to (e.g. VAT Payable)', limit_choices_to={'type': 'LIABILITY'}, on_delete=django.db.models.deletion.RESTRICT, related_name='taxes', to='finance.account'),
        ),
        migrations.AddIndex(
            model_name='receiptallocation',
            index=models.Index(fields=['receipt', 'invoice'], name='finance_rec_receipt_c370dc_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptallocation',
            index=models.Index(fields=['invoice_item'], name='finance_rec_invoice_008493_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='receiptallocation',
            unique_together={('receipt', 'invoice_item')},
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['student', 'received_date'], name='finance_rec_student_7f5829_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='finance_rec_receipt_e3529a_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['is_posted'], name='finance_rec_is_post_4f2edf_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprepayment',
            index=models.Index(fields=['student', 'is_fully_used'], name='finance_stu_student_11d35e_idx'),
        ),
    ]
