# Generated by Django 6.0.3 on 2026-07-27 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Auto-generated name, e.g., 'Grade 1 - Term 1 2026'", max_length=150)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='scheduled', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class Session',
                'verbose_name_plural': 'Class Sessions',
                'db_table': 'class_sessions',
                'ordering': ['academic_year__start_date', 'term__start_date', 'grade__level_order'],
            },
        ),
        migrations.CreateModel(
            name='StudentSessionEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('transferred_out', 'Transferred Out'), ('dropped', 'Dropped'), ('expelled', 'Expelled')], default='active', max_length=20)),
                ('progression_status', models.CharField(choices=[('promoted', 'Promoted'), ('retained', 'Retained/Repeated'), ('graduated', 'Graduated'), ('discontinued', 'Discontinued'), ('pending', 'Pending Decision')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text="Is this the student's CURRENT active session?")),
                ('reporting_date', models.DateField(default=django.utils.timezone.now)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_session_enrollments',
            },
        ),
    ]
