# Generated by Django 6.0.3 on 2026-07-27 14:33

import django.db.models.functions.datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_issued', models.DateField(default=django.db.models.functions.datetime.Now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('OVERDUE', 'Overdue'), ('VOID', 'Void')], default='DRAFT', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_issued', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='FeeInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_optional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Tuition Fee, Activity Fee', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_optional', models.BooleanField(default=False, help_text='If True, student can opt-out (e.g. Transport, Lunch). If False, item is mandatory.')),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One Time'), ('RECURRING', 'Recurring (Termly)'), ('YEARLY', 'Yearly')], default='RECURRING', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Order on invoice (lower first)')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['-academic_year', 'grade', 'term'],
            },
        ),
        migrations.CreateModel(
            name='FeeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=20)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fee Template',
                'verbose_name_plural': 'Fee Templates',
                'ordering': ['-academic_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grade Band',
                'verbose_name_plural': 'Grade Bands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_boarder', models.BooleanField(default=False, help_text='Student uses boarding facilities')),
                ('uses_transport', models.BooleanField(default=False, help_text='Student uses school transport')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Fee Profile',
                'verbose_name_plural': 'Student Fee Profiles',
            },
        ),
        migrations.CreateModel(
            name='TemplateLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_mandatory', models.BooleanField(default=True, help_text='If False, this is an optional item students can opt out of.')),
                ('is_credit_hour', models.BooleanField(default=False, help_text="If True, this line item fee is multiplied by the student's total course credits instead of being billed as a flat rate")),
                ('applies_to', models.CharField(choices=[('ALL', 'All Students'), ('BOARDERS', 'Boarders Only'), ('DAY_SCHOLARS', 'Day Scholars Only')], default='ALL', help_text='Which students this line item applies to.', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Display order (lower first)')),
            ],
            options={
                'verbose_name': 'Template Line Item',
                'verbose_name_plural': 'Template Line Items',
                'ordering': ['priority', 'vote_head__name'],
            },
        ),
        migrations.CreateModel(
            name='VoteHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Tuition Fee, Boarding Fee', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code e.g. TUI, BRD, TRN', max_length=20, unique=True)),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One Time'), ('RECURRING', 'Recurring (Termly)'), ('YEARLY', 'Yearly')], default='RECURRING', max_length=20)),
                ('is_optional', models.BooleanField(default=False, help_text='If True, item can be opted out (e.g. Transport, Lunch).')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vote Head',
                'verbose_name_plural': 'Vote Heads',
                'ordering': ['name'],
            },
        ),
    ]
