# Generated by Django 6.0.1 on 2026-01-30 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0007_paymentmethod_name'),
        ('student_settings', '0005_gradestructure_curriculum_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text="Legacy field, prefer status='ACTIVE'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='student_settings.academicyear')),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='student_settings.curriculum')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='student_settings.gradestructure')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='student_settings.term')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['-academic_year', 'grade', 'term'],
                'unique_together': {('academic_year', 'term', 'grade', 'curriculum')},
            },
        ),
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Tuition Fee, Activity Fee', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_optional', models.BooleanField(default=False, help_text='If True, student can opt-out (e.g. Transport). overrides mandatory.')),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One Time'), ('RECURRING', 'Recurring (Termly)'), ('YEARLY', 'Yearly')], default='RECURRING', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Order on invoice (lower first)')),
                ('account', models.ForeignKey(help_text='Projected Account for posting. MUST be Income or Liability.', limit_choices_to={'is_student_related': True}, on_delete=django.db.models.deletion.PROTECT, related_name='fee_items', to='finance.account')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.feestructure')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
