# Generated by Django 6.0.3 on 2026-07-27 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('fees', '0001_initial'),
        ('finance', '0001_initial'),
        ('student_management', '0001_initial'),
        ('student_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeinvoice',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_settings.academicyear'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='class_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.classsession'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_invoices', to='student_management.student'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='student_enrollment',
            field=models.ForeignKey(help_text='The billing anchor - must exist before invoice creation', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='academics.studentsessionenrollment'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_settings.term'),
        ),
        migrations.AddField(
            model_name='feeinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.feeinvoice'),
        ),
        migrations.AddField(
            model_name='feeitem',
            name='account',
            field=models.ForeignKey(help_text='Account for journal posting. MUST be Income or Liability.', limit_choices_to={'is_student_related': True}, on_delete=django.db.models.deletion.PROTECT, related_name='fee_items', to='finance.account'),
        ),
        migrations.AddField(
            model_name='feeinvoiceitem',
            name='fee_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoiced_items', to='fees.feeitem'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='student_settings.academicyear'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='curriculum',
            field=models.ForeignKey(blank=True, help_text='Required for CBC/8-4-4 differentiated billing', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='student_settings.curriculum'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='student_settings.gradestructure'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='student_settings.term'),
        ),
        migrations.AddField(
            model_name='feeitem',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.feestructure'),
        ),
        migrations.AddField(
            model_name='feetemplate',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_templates', to='student_settings.academicyear'),
        ),
        migrations.AddField(
            model_name='feetemplate',
            name='cohort',
            field=models.ForeignKey(blank=True, help_text='Link this fee template to a specific cohort intake for locked entry pricing', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_templates', to='student_settings.intake'),
        ),
        migrations.AddField(
            model_name='feetemplate',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_templates', to='student_settings.curriculum'),
        ),
        migrations.AddField(
            model_name='feetemplate',
            name='grades',
            field=models.ManyToManyField(blank=True, help_text='Direct grade assignment (overrides band for matching).', related_name='fee_templates', to='student_settings.gradestructure'),
        ),
        migrations.AddField(
            model_name='feetemplate',
            name='parent_template',
            field=models.ForeignKey(blank=True, help_text='Source template this was cloned from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_templates', to='fees.feetemplate'),
        ),
        migrations.AddField(
            model_name='feetemplate',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_templates', to='student_settings.term'),
        ),
        migrations.AddField(
            model_name='gradeband',
            name='grades',
            field=models.ManyToManyField(help_text='Grades in this band share the same fee template.', related_name='fee_bands', to='student_settings.gradestructure'),
        ),
        migrations.AddField(
            model_name='feetemplate',
            name='grade_band',
            field=models.ForeignKey(blank=True, help_text='Apply to all grades in this band.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_templates', to='fees.gradeband'),
        ),
        migrations.AddField(
            model_name='studentfeeprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_profile', to='student_management.student'),
        ),
        migrations.AddField(
            model_name='templatelineitem',
            name='override_account',
            field=models.ForeignKey(blank=True, help_text="Override the vote head's default account for this template only.", limit_choices_to={'is_student_related': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_line_overrides', to='finance.account'),
        ),
        migrations.AddField(
            model_name='templatelineitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='fees.feetemplate'),
        ),
        migrations.AddField(
            model_name='votehead',
            name='default_account',
            field=models.ForeignKey(help_text='Default income/liability account. Can be overridden per template.', limit_choices_to={'is_student_related': True}, on_delete=django.db.models.deletion.PROTECT, related_name='vote_heads', to='finance.account'),
        ),
        migrations.AddField(
            model_name='templatelineitem',
            name='vote_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_lines', to='fees.votehead'),
        ),
        migrations.AddField(
            model_name='studentfeeprofile',
            name='custom_items',
            field=models.ManyToManyField(blank=True, help_text='Additional optional vote heads this student is enrolled in.', related_name='opted_in_students', to='fees.votehead'),
        ),
        migrations.AddField(
            model_name='feeinvoiceitem',
            name='vote_head',
            field=models.ForeignKey(blank=True, help_text='Set for template-based invoices. Null for legacy FeeItem invoices.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoiced_items', to='fees.votehead'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'VOID'), _negated=True), fields=('student_enrollment',), name='unique_active_invoice_per_enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('academic_year', 'term', 'grade', 'curriculum')},
        ),
        migrations.AlterUniqueTogether(
            name='templatelineitem',
            unique_together={('template', 'vote_head')},
        ),
        migrations.AddConstraint(
            model_name='feeinvoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('fee_item__isnull', False)), fields=('invoice', 'fee_item'), name='unique_legacy_fee_item_per_invoice'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('vote_head__isnull', False)), fields=('invoice', 'vote_head'), name='unique_vote_head_per_invoice'),
        ),
    ]
