# Generated by Django 6.0.1 on 2026-02-02 12:40

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0009_student_status'),
        ('fees', '0001_initial'),
        ('student_settings', '0007_admissionconfig_include_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_issued', models.DateField(default=django.db.models.functions.datetime.Now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('OVERDUE', 'Overdue'), ('VOID', 'Void')], default='DRAFT', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_settings.academicyear')),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_invoices', to='accounts.student')),
                ('student_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='academics.studentsessionenrollment')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_settings.term')),
            ],
            options={
                'ordering': ['-date_issued', '-invoice_number'],
                'unique_together': {('student_enrollment',)},
            },
        ),
        migrations.CreateModel(
            name='FeeInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoiced_items', to='fees.feeitem')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.feeinvoice')),
            ],
            options={
                'unique_together': {('invoice', 'fee_item')},
            },
        ),
    ]
