# Generated by Django 6.0.2 on 2026-03-11 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        (
            "accounts",
            "0011_student_allergies_student_birth_certificate_number_and_more",
        ),
        ("fees", "0002_feeinvoice_feeinvoiceitem"),
        ("finance", "0013_alter_receiptallocation_invoice_and_more"),
        ("student_settings", "0009_learningarea"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="feeinvoice",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="feeinvoiceitem",
            name="is_mandatory",
        ),
        migrations.RemoveField(
            model_name="feeitem",
            name="is_mandatory",
        ),
        migrations.RemoveField(
            model_name="feestructure",
            name="is_active",
        ),
        migrations.AddField(
            model_name="feeinvoiceitem",
            name="is_optional",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="feeinvoice",
            name="student_enrollment",
            field=models.ForeignKey(
                help_text="The billing anchor - must exist before invoice creation",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="academics.studentsessionenrollment",
            ),
        ),
        migrations.AlterField(
            model_name="feeitem",
            name="account",
            field=models.ForeignKey(
                help_text="Account for journal posting. MUST be Income or Liability.",
                limit_choices_to={"is_student_related": True},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_items",
                to="finance.account",
            ),
        ),
        migrations.AlterField(
            model_name="feeitem",
            name="is_optional",
            field=models.BooleanField(
                default=False,
                help_text="If True, student can opt-out (e.g. Transport, Lunch). If False, item is mandatory.",
            ),
        ),
        migrations.AlterField(
            model_name="feestructure",
            name="curriculum",
            field=models.ForeignKey(
                blank=True,
                help_text="Required for CBC/8-4-4 differentiated billing",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_structures",
                to="student_settings.curriculum",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeinvoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "VOID"), _negated=True),
                fields=("student_enrollment",),
                name="unique_active_invoice_per_enrollment",
            ),
        ),
    ]
