# Generated by Django 6.0.3 on 2026-04-10 12:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_student_campus'),
        ('fees', '0003_alter_feeinvoice_unique_together_and_more'),
        ('finance', '0014_financesettings_default_sundry_debtors_account'),
        ('student_settings', '0012_enrollment_campus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feeinvoiceitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='feeinvoiceitem',
            name='fee_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoiced_items', to='fees.feeitem'),
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grades', models.ManyToManyField(help_text='Grades in this band share the same fee template.', related_name='fee_bands', to='student_settings.gradestructure')),
            ],
            options={
                'verbose_name': 'Grade Band',
                'verbose_name_plural': 'Grade Bands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=20)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_templates', to='student_settings.academicyear')),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_templates', to='student_settings.curriculum')),
                ('grades', models.ManyToManyField(blank=True, help_text='Direct grade assignment (overrides band for matching).', related_name='fee_templates', to='student_settings.gradestructure')),
                ('parent_template', models.ForeignKey(blank=True, help_text='Source template this was cloned from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_templates', to='fees.feetemplate')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_templates', to='student_settings.term')),
                ('grade_band', models.ForeignKey(blank=True, help_text='Apply to all grades in this band.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_templates', to='fees.gradeband')),
            ],
            options={
                'verbose_name': 'Fee Template',
                'verbose_name_plural': 'Fee Templates',
                'ordering': ['-academic_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VoteHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Tuition Fee, Boarding Fee', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code e.g. TUI, BRD, TRN', max_length=20, unique=True)),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One Time'), ('RECURRING', 'Recurring (Termly)'), ('YEARLY', 'Yearly')], default='RECURRING', max_length=20)),
                ('is_optional', models.BooleanField(default=False, help_text='If True, item can be opted out (e.g. Transport, Lunch).')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_account', models.ForeignKey(help_text='Default income/liability account. Can be overridden per template.', limit_choices_to={'is_student_related': True}, on_delete=django.db.models.deletion.PROTECT, related_name='vote_heads', to='finance.account')),
            ],
            options={
                'verbose_name': 'Vote Head',
                'verbose_name_plural': 'Vote Heads',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_mandatory', models.BooleanField(default=True, help_text='If False, this is an optional item students can opt out of.')),
                ('priority', models.IntegerField(default=0, help_text='Display order (lower first)')),
                ('override_account', models.ForeignKey(blank=True, help_text="Override the vote head's default account for this template only.", limit_choices_to={'is_student_related': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_line_overrides', to='finance.account')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='fees.feetemplate')),
                ('vote_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_lines', to='fees.votehead')),
            ],
            options={
                'verbose_name': 'Template Line Item',
                'verbose_name_plural': 'Template Line Items',
                'ordering': ['priority', 'vote_head__name'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_boarder', models.BooleanField(default=False, help_text='Student uses boarding facilities')),
                ('uses_transport', models.BooleanField(default=False, help_text='Student uses school transport')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_profile', to='accounts.student')),
                ('custom_items', models.ManyToManyField(blank=True, help_text='Additional optional vote heads this student is enrolled in.', related_name='opted_in_students', to='fees.votehead')),
            ],
            options={
                'verbose_name': 'Student Fee Profile',
                'verbose_name_plural': 'Student Fee Profiles',
            },
        ),
        migrations.AddField(
            model_name='feeinvoiceitem',
            name='vote_head',
            field=models.ForeignKey(blank=True, help_text='Set for template-based invoices. Null for legacy FeeItem invoices.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoiced_items', to='fees.votehead'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('fee_item__isnull', False)), fields=('invoice', 'fee_item'), name='unique_legacy_fee_item_per_invoice'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('vote_head__isnull', False)), fields=('invoice', 'vote_head'), name='unique_vote_head_per_invoice'),
        ),
        migrations.AlterUniqueTogether(
            name='templatelineitem',
            unique_together={('template', 'vote_head')},
        ),
    ]
