# Generated by Django 6.0.3 on 2026-04-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0004_fee_template_architecture"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatelineitem",
            name="applies_to",
            field=models.CharField(
                choices=[
                    ("ALL", "All Students"),
                    ("BOARDERS", "Boarders Only"),
                    ("DAY_SCHOLARS", "Day Scholars Only"),
                ],
                default="ALL",
                help_text="Which students this line item applies to.",
                max_length=20,
            ),
        ),
    ]
