# Generated by Django 6.0.3 on 2026-05-21 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0005_templatelineitem_applies_to"),
        ("student_settings", "0014_gradestructure_credits_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feetemplate",
            name="cohort",
            field=models.ForeignKey(
                blank=True,
                help_text="Link this fee template to a specific cohort intake for locked entry pricing",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_templates",
                to="student_settings.intake",
            ),
        ),
        migrations.AddField(
            model_name="templatelineitem",
            name="is_credit_hour",
            field=models.BooleanField(
                default=False,
                help_text="If True, this line item fee is multiplied by the student's total course credits instead of being billed as a flat rate",
            ),
        ),
    ]
