# Generated by Django 6.0.3 on 2026-07-27 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0002_initial'),
        ('finance', '0001_initial'),
        ('payables', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Link to purchase order for 3-way matching', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='payables.supplier'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='supplier_invoice',
            field=models.ForeignKey(blank=True, help_text='Required for AP voucher type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_vouchers', to='payables.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='budget_line',
            field=models.ForeignKey(blank=True, help_text='Budget line for IPSAS 24 tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_lines', to='budgets.budgetline'),
        ),
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='gl_account',
            field=models.ForeignKey(limit_choices_to={'type__in': ['EXPENSE', 'LIABILITY', 'ASSET']}, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_lines', to='finance.account'),
        ),
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payables.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='bill',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payables.vendor'),
        ),
        migrations.AddField(
            model_name='voucherapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherapproval',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='payables.paymentvoucher'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierinvoice',
            unique_together={('supplier', 'invoice_number')},
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('vendor', 'bill_number')},
        ),
    ]
