# Generated by Django 6.0.2 on 2026-03-11 11:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0001_initial"),
        ("finance", "0013_alter_receiptallocation_invoice_and_more"),
        ("journals", "0001_initial"),
        ("payables", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Bursar Only', 'Principal Required'",
                        max_length=100,
                    ),
                ),
                ("min_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "required_roles",
                    models.JSONField(
                        default=list,
                        help_text="List of role names required to approve, in order. e.g. ['BURSAR', 'PRINCIPAL']",
                    ),
                ),
                (
                    "voucher_types",
                    models.JSONField(
                        default=list,
                        help_text="List of voucher types: AP, GENERAL, IMPREST, REFUND, or ALL",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Approval Threshold",
                "verbose_name_plural": "Approval Thresholds",
                "ordering": ["min_amount"],
            },
        ),
        migrations.AlterModelOptions(
            name="bill",
            options={
                "ordering": ["-date_received", "bill_number"],
                "verbose_name": "Bill (Legacy)",
                "verbose_name_plural": "Bills (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="vendor",
            options={
                "verbose_name": "Vendor (Legacy)",
                "verbose_name_plural": "Vendors (Legacy)",
            },
        ),
        migrations.AlterField(
            model_name="bill",
            name="journal_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_bill",
                to="journals.journalentry",
            ),
        ),
        migrations.AlterField(
            model_name="billline",
            name="expense_account",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    ("type", "EXPENSE"), ("type", "ASSET"), _connector="OR"
                ),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legacy_bill_lines",
                to="finance.account",
            ),
        ),
        migrations.AlterModelTable(
            name="bill",
            table="vendor_bills",
        ),
        migrations.AlterModelTable(
            name="vendor",
            table="vendors",
        ),
        migrations.CreateModel(
            name="ImprestRetirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("retirement_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "surrender_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cash returned from imprest",
                        max_digits=15,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_retirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imprest_retirement",
                        to="journals.journalentry",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_retirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_retirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Imprest Retirement",
                "verbose_name_plural": "Imprest Retirements",
                "db_table": "imprest_surrender",
                "ordering": ["-retirement_date"],
            },
        ),
        migrations.CreateModel(
            name="ImprestRetirementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("receipt_date", models.DateField(blank=True, null=True)),
                (
                    "gl_account",
                    models.ForeignKey(
                        limit_choices_to={"type": "EXPENSE"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imprest_retirement_lines",
                        to="finance.account",
                    ),
                ),
                (
                    "retirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="payables.imprestretirement",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("AP", "Accounts Payable"),
                            ("GENERAL", "General Payment"),
                            ("IMPREST", "Imprest/Cash Advance"),
                            ("REFUND", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                            ("VOID", "Void"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.CharField(default="KES", max_length=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("MPESA", "M-Pesa"),
                            ("EFT", "Electronic Funds Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("CASH", "Cash"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="M-Pesa code, Cheque number, or EFT reference",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "payee_name",
                    models.CharField(
                        blank=True,
                        help_text="Required for GENERAL and REFUND types",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "approval_chain",
                    models.JSONField(
                        default=list,
                        help_text="Required approval steps from ApprovalThreshold",
                    ),
                ),
                ("current_approval_step", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        help_text="School's bank account to debit",
                        limit_choices_to={"is_for_payment": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_vouchers",
                        to="finance.paymentmethod",
                    ),
                ),
                (
                    "imprest_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Imprest account for tracking advances",
                        limit_choices_to={"sub_type": "PREPAYMENTS"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imprest_vouchers",
                        to="finance.account",
                    ),
                ),
                (
                    "journal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_voucher",
                        to="journals.journalentry",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paid_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prepared_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "refund_receipt",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original receipt being refunded (REFUND type)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_vouchers",
                        to="finance.receipt",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for IMPREST type",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imprest_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Voucher",
                "verbose_name_plural": "Payment Vouchers",
                "db_table": "payment_voucher",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="imprestretirement",
            name="voucher",
            field=models.OneToOneField(
                limit_choices_to={"voucher_type": "IMPREST"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="retirement",
                to="payables.paymentvoucher",
            ),
        ),
        migrations.CreateModel(
            name="PaymentVoucherLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "budget_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_voucher_lines",
                        to="budgets.budgetline",
                    ),
                ),
                (
                    "gl_account",
                    models.ForeignKey(
                        limit_choices_to={"type__in": ["EXPENSE", "ASSET"]},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_voucher_lines",
                        to="finance.account",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="payables.paymentvoucher",
                    ),
                ),
            ],
            options={
                "db_table": "voucher_details",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "kra_pin",
                    models.CharField(
                        help_text="KRA PIN in format: A000000000A",
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="KRA PIN must be in format: A000000000A (letter, 9 digits, letter)",
                                regex="^[A-Z]\\d{9}[A-Z]$",
                            )
                        ],
                    ),
                ),
                ("vat_registered", models.BooleanField(default=False)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bank_branch",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "bank_code",
                    models.CharField(
                        blank=True,
                        help_text="Swift/Bank Code",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash on Delivery"),
                            ("NET_7", "Net 7 Days"),
                            ("NET_14", "Net 14 Days"),
                            ("NET_30", "Net 30 Days"),
                        ],
                        default="NET_30",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ap_account",
                    models.ForeignKey(
                        help_text="Accounts Payable account for this supplier",
                        limit_choices_to={"type": "LIABILITY"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suppliers",
                        to="finance.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_suppliers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "db_table": "supplier",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual Entry"),
                            ("PROCUREMENT", "From Procurement"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "purchase_order_ref",
                    models.CharField(
                        blank=True,
                        help_text="Purchase Order reference when source=PROCUREMENT",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Supplier's invoice number", max_length=50
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField()),
                ("currency", models.CharField(default="KES", max_length=10)),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("PAID", "Paid"),
                            ("VOID", "Void"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_supplier_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_supplier_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_invoice",
                        to="journals.journalentry",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_supplier_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="payables.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Invoice",
                "verbose_name_plural": "Supplier Invoices",
                "db_table": "supplier_invoices",
                "ordering": ["-invoice_date", "-created_at"],
                "unique_together": {("supplier", "invoice_number")},
            },
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="supplier_invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="Required for AP voucher type",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_vouchers",
                to="payables.supplierinvoice",
            ),
        ),
        migrations.CreateModel(
            name="SupplierInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=12
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        choices=[
                            (Decimal("0.00"), "0%"),
                            (Decimal("8.00"), "8%"),
                            (Decimal("16.00"), "16%"),
                        ],
                        decimal_places=2,
                        default=Decimal("16.00"),
                        max_digits=5,
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "budget_line",
                    models.ForeignKey(
                        blank=True,
                        help_text="Budget line for IPSAS 24 tracking",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_invoice_lines",
                        to="budgets.budgetline",
                    ),
                ),
                (
                    "gl_account",
                    models.ForeignKey(
                        limit_choices_to={"type__in": ["EXPENSE", "ASSET"]},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_invoice_lines",
                        to="finance.account",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="payables.supplierinvoice",
                    ),
                ),
            ],
            options={
                "db_table": "supplier_invoice_lines",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="VoucherApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Role the approver is acting as (e.g. BURSAR, PRINCIPAL)",
                        max_length=50,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voucher_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="payables.paymentvoucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voucher Approval",
                "verbose_name_plural": "Voucher Approvals",
                "db_table": "voucher_approval",
                "ordering": ["approved_at"],
            },
        ),
    ]
