# Generated by Django 6.0.2 on 2026-03-11 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0013_alter_receiptallocation_invoice_and_more"),
        ("payables", "0002_approvalthreshold_alter_bill_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="ap_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Accounts Payable account (uses default from settings if blank)",
                limit_choices_to={"type": "LIABILITY"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suppliers",
                to="finance.account",
            ),
        ),
    ]
