# Generated by Django 6.0.2 on 2026-03-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payables", "0003_supplier_ap_account_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="code",
            field=models.CharField(
                blank=True, editable=False, max_length=20, unique=True
            ),
        ),
    ]
