# Generated by Django 6.0.2 on 2026-03-11 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payables", "0004_supplier_add_code_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="kra_pin",
            field=models.CharField(
                blank=True,
                help_text="KRA PIN in format: A000000000A (optional)",
                max_length=11,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="KRA PIN must be in format: A000000000A (letter, 9 digits, letter)",
                        regex="^[A-Z]\\d{9}[A-Z]$",
                    )
                ],
            ),
        ),
    ]
