# Generated by Django 6.0.2 on 2026-03-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payables", "0005_supplier_kra_pin_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentvoucher",
            name="description",
            field=models.TextField(
                blank=True, help_text="Payment description", null=True
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="refund_reason",
            field=models.TextField(
                blank=True, help_text="Reason for refund", null=True
            ),
        ),
    ]
