# Generated by Django 6.0.2 on 2026-03-11 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0013_alter_receiptallocation_invoice_and_more"),
        ("payables", "0006_payment_voucher_add_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentvoucher",
            name="cheque_number",
            field=models.CharField(
                blank=True,
                help_text="Cheque number (for cheque payments)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                help_text="School's bank account to debit",
                limit_choices_to={"is_for_payment": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_vouchers",
                to="finance.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                help_text="M-Pesa code or EFT reference",
                max_length=100,
                null=True,
            ),
        ),
    ]
