# Generated by Django 6.0.2 on 2026-03-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payables", "0007_payment_voucher_add_cheque_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentvoucher",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("CHEQUE", "Cheque"),
                    ("CASH", "Cash"),
                    ("MOBILE_MONEY", "Mobile Money (M-Pesa)"),
                ],
                max_length=20,
            ),
        ),
    ]
