# Generated by Django 6.0.2 on 2026-03-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payables", "0008_alter_paymentvoucher_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentvoucher",
            name="approval_chain",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Required approval steps from ApprovalThreshold",
            ),
        ),
    ]
