# Generated by Django 6.0.2 on 2026-03-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payables", "0009_approval_chain_allow_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierinvoice",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Scanned invoice or supporting document",
                null=True,
                upload_to="supplier_invoices/%Y/%m/",
            ),
        ),
    ]
