# Generated by Django 6.0.3 on 2026-04-15 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_account_available_in_payroll'),
        ('payables', '0010_add_supplier_invoice_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucherline',
            name='gl_account',
            field=models.ForeignKey(limit_choices_to={'type__in': ['EXPENSE', 'LIABILITY', 'ASSET']}, on_delete=django.db.models.deletion.PROTECT, related_name='payment_voucher_lines', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='supplierinvoiceline',
            name='gl_account',
            field=models.ForeignKey(limit_choices_to={'type__in': ['EXPENSE', 'LIABILITY', 'ASSET']}, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_lines', to='finance.account'),
        ),
    ]
