# Generated by Django 6.0.3 on 2026-08-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionprofile",
            name="business_sector",
            field=models.CharField(
                choices=[
                    ("education", "Education & Academic"),
                    ("retail", "Retail & Commerce"),
                    ("healthcare", "Healthcare"),
                    ("corporate", "Corporate / Services"),
                    ("ngo", "Non-Governmental Organization"),
                    ("general", "General Business"),
                ],
                default="education",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="institutionprofile",
            name="enabled_modules",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of enabled modules e.g., ["academics", "hr", "procurement"]',
                null=True,
            ),
        ),
    ]
