# Generated by Django 6.0.3 on 2026-08-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_institutionprofile_business_sector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionprofile",
            name="admission_letter_template",
            field=models.TextField(
                blank=True,
                help_text="HTML template for the official admission letter body",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="institutionprofile",
            name="offer_letter_template",
            field=models.TextField(
                blank=True,
                help_text="HTML template for the conditional offer letter body",
                null=True,
            ),
        ),
    ]
