# Generated by Django 6.0.3 on 2026-08-29 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_institutionprofile_admission_letter_template_and_more"),
        ("finance", "0002_initial"),
        ("payables", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSPricingBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Band A (up to 4000 SMS)", max_length=100
                    ),
                ),
                (
                    "max_sms",
                    models.PositiveIntegerField(
                        help_text="Maximum SMS count for this band (inclusive)"
                    ),
                ),
                (
                    "fixed_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Flat cost for this band",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Pricing Band",
                "verbose_name_plural": "SMS Pricing Bands",
                "db_table": "core_sms_pricing_band",
                "ordering": ["max_sms"],
            },
        ),
        migrations.CreateModel(
            name="BillingCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="First day of the billed month (e.g., 2026-08-01)",
                        unique=True,
                    ),
                ),
                ("invoice_generated", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payables.supplierinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Cycle",
                "verbose_name_plural": "Billing Cycles",
                "db_table": "core_billing_cycle",
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="SystemSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package_name",
                    models.CharField(default="Standard Package", max_length=100),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "ai_markup_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Markup applied to raw AI cost (e.g. 20.00 for 20%)",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ap_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Accounts Payable account to credit when generating platform bills",
                        limit_choices_to={"type": "LIABILITY"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Subscription",
                "verbose_name_plural": "System Subscriptions",
                "db_table": "core_system_subscription",
            },
        ),
    ]
