# Generated by Django 6.0.3 on 2026-08-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentplacement',
            name='student_pla_student_de839e_idx',
        ),
        migrations.DeleteModel(
            name='StudentPlacement',
        ),
    ]
