# Generated by Django 6.0.1 on 2026-01-27 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otp'),
        ('student_settings', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, help_text='Date when student was admitted to the school', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='intake_year',
            field=models.ForeignKey(blank=True, help_text='The academic year when this student was first admitted to the school', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intake_students', to='student_settings.academicyear'),
        ),
    ]
