# Generated by Django 6.0.1 on 2026-01-27 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_admission_date_student_intake_year'),
        ('student_settings', '0003_intake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='intake_year',
        ),
        migrations.AddField(
            model_name='student',
            name='intake',
            field=models.ForeignKey(blank=True, help_text='The intake cohort this student belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='student_settings.intake'),
        ),
    ]
