# Generated by Django 6.0.1 on 2026-01-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_student_level_remove_student_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('alumni', 'Alumni'), ('suspended', 'Suspended'), ('expelled', 'Expelled'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn')], default='active', max_length=20),
        ),
    ]
