# Generated by Django 6.0.2 on 2026-03-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="allergies",
            field=models.TextField(blank=True, help_text="Known allergies", null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="birth_certificate_number",
            field=models.CharField(
                blank=True,
                help_text="Birth certificate number",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="emergency_contact_relationship",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="home_address",
            field=models.TextField(
                blank=True, help_text="Physical home address", null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="medical_conditions",
            field=models.TextField(
                blank=True, help_text="Any known medical conditions", null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="previous_class",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="previous_school_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="previous_school_leaving_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="previous_school_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="special_needs",
            field=models.TextField(
                blank=True,
                help_text="Special educational needs or requirements",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="transfer_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="nationality",
            field=models.CharField(
                blank=True, default="Kenyan", max_length=100, null=True
            ),
        ),
    ]
