# Generated by Django 6.0.3 on 2026-04-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0011_student_allergies_student_birth_certificate_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelTable(
            name="user",
            table="auth_user",
        ),
    ]
