# Generated by Django 6.0.3 on 2026-04-09 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_options_alter_user_table'),
        ('workforce', '0008_add_institution_to_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Primary campus this student belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='workforce.campus'),
        ),
    ]
