# Generated by Django 6.0.3 on 2026-04-17 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_student_campus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parents",
                to="accounts.student",
            ),
        ),
    ]
