# Generated by Django 6.0.3 on 2026-05-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_timeout',
            field=models.IntegerField(default=30, help_text='Inactivity timeout in minutes for current session'),
        ),
    ]
