# Generated by Django 6.0.3 on 2026-08-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_publicconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="domain",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("suspended", "Suspended")],
                default="active",
                max_length=20,
            ),
        ),
    ]
