# Generated by Django 6.0.1 on 2026-01-26 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otp'),
        ('student_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('promoted', 'Promoted'), ('repeated', 'Repeated'), ('transferred_out', 'Transferred Out'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('enrollment_type', models.CharField(choices=[('new_admission', 'New Admission'), ('promotion', 'Promotion'), ('repeat', 'Repeat'), ('transfer_in', 'Transfer In'), ('curriculum_change', 'Curriculum Change')], default='new_admission', max_length=20)),
                ('enrollment_date', models.DateField(help_text='Date when student was enrolled')),
                ('exit_date', models.DateField(blank=True, help_text='Date when enrollment ended', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Reason for enrollment, transfer, or any special notes', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active enrollment per student per term')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='student_settings.academicyear')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='student_settings.curriculum')),
                ('grade', models.ForeignKey(help_text='Class/Grade level', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='student_settings.gradestructure')),
                ('previous_enrollment', models.ForeignKey(blank=True, help_text='Links to previous enrollment for progression tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_enrollments', to='student_settings.enrollment')),
                ('stream', models.ForeignKey(blank=True, help_text='Section/Stream within the class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='student_settings.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='student_settings.term')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrollment_date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'academic_year', 'term'], name='student_set_student_24b25c_idx'), models.Index(fields=['status', 'is_active'], name='student_set_status_05f2ad_idx'), models.Index(fields=['enrollment_date'], name='student_set_enrollm_4d31bc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('student', 'academic_year', 'term'), name='unique_active_enrollment_per_term')],
            },
        ),
    ]
