# Generated by Django 6.0.1 on 2026-01-27 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_settings', '0002_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='e.g., "2024 Intake", "Class of 2024"', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code, e.g., "INT2024"', max_length=20, unique=True)),
                ('start_date', models.DateField(help_text='When this intake cohort started')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this intake is currently accepting students')),
                ('academic_year', models.ForeignKey(help_text='Academic year for this intake cohort', on_delete=django.db.models.deletion.PROTECT, related_name='intakes', to='student_settings.academicyear')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intake',
                'verbose_name_plural': 'Intakes',
                'ordering': ['-academic_year__start_date', '-start_date'],
            },
        ),
    ]
