# Generated by Django 6.0.1 on 2026-01-27 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_settings', '0003_intake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('phased_out', 'Phased Out')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='intake',
            name='admission_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('transfer', 'Transfer'), ('re_entry', 'Re-entry')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='intake',
            name='entry_curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intakes', to='student_settings.curriculum'),
        ),
        migrations.AddField(
            model_name='intake',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='CurriculumLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(help_text='Order in the curriculum progression')),
                ('min_years', models.PositiveIntegerField(blank=True, help_text='Minimum years to complete this level', null=True)),
                ('max_years', models.PositiveIntegerField(blank=True, help_text='Maximum years allowed for this level', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='student_settings.curriculum')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['curriculum', 'order'],
                'unique_together': {('curriculum', 'name')},
            },
        ),
        migrations.AddField(
            model_name='intake',
            name='entry_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intakes', to='student_settings.curriculumlevel'),
        ),
    ]
