# Generated by Django 6.0.1 on 2026-01-27 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_settings', '0004_curriculum_status_intake_admission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradestructure',
            name='curriculum_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='student_settings.curriculumlevel'),
        ),
    ]
