# Generated by Django 6.0.1 on 2026-01-30 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_settings', '0005_gradestructure_curriculum_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='entry_grade',
            field=models.ForeignKey(blank=True, help_text='Specific grade level for entry (e.g., Grade 1)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intakes', to='student_settings.gradestructure'),
        ),
    ]
