# Generated by Django 6.0.1 on 2026-01-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_settings', '0006_intake_entry_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionconfig',
            name='include_year',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admissionconfig',
            name='separator',
            field=models.CharField(blank=True, default='/', max_length=5),
        ),
        migrations.AddField(
            model_name='admissionconfig',
            name='sequence_format',
            field=models.CharField(choices=[('P-Y-S', 'Prefix - Year - Serial'), ('P-S-Y', 'Prefix - Serial - Year'), ('Y-P-S', 'Year - Prefix - Serial'), ('P-S', 'Prefix - Serial')], default='P-Y-S', max_length=10),
        ),
        migrations.AddField(
            model_name='admissionconfig',
            name='year_format',
            field=models.CharField(choices=[('YYYY', 'Full Year (e.g. 2026)'), ('YY', 'Last 2 Digits (e.g. 26)')], default='YYYY', max_length=4),
        ),
        migrations.AlterField(
            model_name='admissionconfig',
            name='prefix',
            field=models.CharField(default='SCH', max_length=20),
        ),
    ]
