# Generated by Django 6.0.1 on 2026-02-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_settings', '0007_admissionconfig_include_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='reporting_reason',
            field=models.CharField(blank=True, help_text="Reason for reporting (e.g., 'Opening Day', 'Late Reporting')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='stay_status',
            field=models.CharField(blank=True, choices=[('day_scholar', 'Day Scholar'), ('boarder', 'Boarder')], default='day_scholar', help_text="Student's residential status for this term", max_length=20, null=True),
        ),
    ]
