# Generated by Django 6.0.3 on 2026-04-07 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_settings", "0009_learningarea"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicyear",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AlterModelOptions(
            name="curriculum",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="schoolcalendar",
            options={"ordering": ["start_date"]},
        ),
        migrations.AlterModelOptions(
            name="stream",
            options={"ordering": ["grade__level_order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="studentstatus",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="term",
            options={"ordering": ["academic_year__start_date", "order"]},
        ),
        migrations.RenameIndex(
            model_name="enrollment",
            new_name="student_enr_student_f98c50_idx",
            old_name="student_set_student_24b25c_idx",
        ),
        migrations.RenameIndex(
            model_name="enrollment",
            new_name="student_enr_status_cda505_idx",
            old_name="student_set_status_05f2ad_idx",
        ),
        migrations.RenameIndex(
            model_name="enrollment",
            new_name="student_enr_enrollm_9a4379_idx",
            old_name="student_set_enrollm_4d31bc_idx",
        ),
        migrations.RemoveField(
            model_name="curriculum",
            name="education_level",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="curriculum_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Level within curriculum (e.g. Primary, JSS, Senior Secondary)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="student_settings.curriculumlevel",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="intake",
            field=models.ForeignKey(
                blank=True,
                help_text="Intake cohort the student belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_enrollments",
                to="student_settings.intake",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stream",
            unique_together={("grade", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="term",
            unique_together={("academic_year", "order")},
        ),
        migrations.AlterModelTable(
            name="academicyear",
            table="academic_years",
        ),
        migrations.AlterModelTable(
            name="admissionconfig",
            table="admission_configs",
        ),
        migrations.AlterModelTable(
            name="curriculum",
            table="curriculums",
        ),
        migrations.AlterModelTable(
            name="curriculumlevel",
            table="curriculum_levels",
        ),
        migrations.AlterModelTable(
            name="demographicconfig",
            table="demographic_configs",
        ),
        migrations.AlterModelTable(
            name="enrollment",
            table="student_enrollments",
        ),
        migrations.AlterModelTable(
            name="gradestructure",
            table="grade_structures",
        ),
        migrations.AlterModelTable(
            name="intake",
            table="intakes",
        ),
        migrations.AlterModelTable(
            name="learningarea",
            table="learning_areas",
        ),
        migrations.AlterModelTable(
            name="promotionrule",
            table="promotion_rules",
        ),
        migrations.AlterModelTable(
            name="schoolcalendar",
            table="school_calendars",
        ),
        migrations.AlterModelTable(
            name="stream",
            table="streams",
        ),
        migrations.AlterModelTable(
            name="studentstatus",
            table="student_statuses",
        ),
        migrations.AlterModelTable(
            name="term",
            table="terms",
        ),
    ]
