# Generated by Django 6.0.3 on 2026-04-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_settings",
            "0010_alter_academicyear_options_alter_curriculum_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionconfig",
            name="require_application",
            field=models.BooleanField(
                default=True,
                help_text="If True, students must have an approved Application before being admitted. Excel bulk import bypasses this requirement.",
            ),
        ),
    ]
