# Generated by Django 6.0.3 on 2026-04-09 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_settings', '0011_admissionconfig_require_application'),
        ('workforce', '0008_add_institution_to_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Campus for this enrollment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='workforce.campus'),
        ),
    ]
