# Generated by Django 6.0.3 on 2026-04-10 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_settings', '0012_enrollment_campus'),
        ('workforce', '0009_employee_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Campus for this enrollment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campus_enrollments', to='workforce.campus'),
        ),
    ]
