# Generated by Django 6.0.3 on 2026-05-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_settings", "0013_fee_template_architecture"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradestructure",
            name="credits_required",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total course credits required to complete this stage (for higher education)",
            ),
        ),
        migrations.AddField(
            model_name="intake",
            name="expected_graduation_date",
            field=models.DateField(
                blank=True,
                help_text="Expected graduation date for this cohort",
                null=True,
            ),
        ),
    ]
