# Generated by Django 6.0.3 on 2026-05-23 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_settings", "0014_gradestructure_credits_required_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionWorkflowConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "require_enquiry",
                    models.BooleanField(
                        default=False,
                        help_text="If True, an Enquiry record must exist and be converted before an Application can be created.",
                    ),
                ),
                (
                    "require_application_fee",
                    models.BooleanField(
                        default=False,
                        help_text="If True, a registration/application fee must be paid (or waived) before the application can proceed.",
                    ),
                ),
                (
                    "require_interview",
                    models.BooleanField(
                        default=False,
                        help_text="If True, an Interview must be scheduled and passed before admission.",
                    ),
                ),
                (
                    "require_reporting",
                    models.BooleanField(
                        default=False,
                        help_text="If True, a Reporting record (student physically arrives with documents) must be marked before formal admission.",
                    ),
                ),
                (
                    "application_fee_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount charged as the application/registration fee.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "application_fee_label",
                    models.CharField(
                        default="Application Registration Fee",
                        help_text="Label shown on receipts and the frontend.",
                        max_length=100,
                    ),
                ),
                (
                    "application_fee_currency",
                    models.CharField(
                        blank=True,
                        default="KES",
                        help_text="Currency code, e.g. KES, USD.",
                        max_length=10,
                    ),
                ),
                (
                    "interview_label",
                    models.CharField(
                        default="Interview",
                        help_text='Label shown in the UI, e.g. "Entrance Interview", "Assessment Day".',
                        max_length=100,
                    ),
                ),
                (
                    "allow_self_schedule",
                    models.BooleanField(
                        default=False,
                        help_text="If True, applicants can pick their own interview slot from available slots.",
                    ),
                ),
                (
                    "reporting_label",
                    models.CharField(
                        default="Reporting & Document Submission",
                        help_text="Label shown in the UI for the reporting stage.",
                        max_length=100,
                    ),
                ),
                (
                    "document_checklist",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of required documents as strings, e.g. ["Birth Certificate", "Passport Photo", "Previous Report Card"]. Displayed as a checklist on the reporting form.',
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admission Workflow Configuration",
                "db_table": "admission_workflow_configs",
            },
        ),
    ]
