# Generated by Django 6.0.3 on 2026-07-27 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('daraja', 'Safaricom Daraja (M-Pesa)'), ('paystack', 'Paystack'), ('africastalking', "Africa's Talking SMS"), ('twilio', 'Twilio SMS'), ('infobip', 'Infobip SMS')], max_length=40)),
                ('label', models.CharField(blank=True, help_text='Friendly name, e.g. "School M-Pesa till"', max_length=80)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox / Test'), ('production', 'Production / Live')], default='sandbox', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('consumer_key', models.CharField(blank=True, max_length=200)),
                ('consumer_secret', models.CharField(blank=True, max_length=200)),
                ('shortcode', models.CharField(blank=True, help_text='Business shortcode (paybill or till number)', max_length=20)),
                ('passkey', models.CharField(blank=True, help_text='Lipa-Na-M-Pesa online passkey', max_length=400)),
                ('callback_url', models.URLField(blank=True, help_text='Public HTTPS URL Safaricom will POST payment results to')),
                ('b2c_initiator_name', models.CharField(blank=True, max_length=100)),
                ('b2c_initiator_password', models.CharField(blank=True, max_length=200)),
                ('b2c_result_url', models.URLField(blank=True)),
                ('b2c_queue_timeout_url', models.URLField(blank=True)),
                ('public_key', models.CharField(blank=True, max_length=200)),
                ('secret_key', models.CharField(blank=True, max_length=200)),
                ('api_key', models.CharField(blank=True, max_length=300)),
                ('api_secret', models.CharField(blank=True, max_length=300)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('sender_id', models.CharField(blank=True, help_text="Alphanumeric sender ID shown on recipient's phone", max_length=20)),
                ('account_sid', models.CharField(blank=True, max_length=100)),
                ('auth_token', models.CharField(blank=True, max_length=200)),
                ('from_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gateway Config',
                'verbose_name_plural': 'Gateway Configs',
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('recipient', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=100)),
                ('cost', models.CharField(blank=True, max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('payment_complete', models.BooleanField(default=False)),
                ('invoice_code', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('daraja', 'Safaricom Daraja (M-Pesa)'), ('paystack', 'Paystack'), ('africastalking', "Africa's Talking SMS"), ('twilio', 'Twilio SMS'), ('infobip', 'Infobip SMS')], max_length=40)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('external_reference', models.CharField(blank=True, help_text='Provider transaction ID, e.g. Safaricom CheckoutRequestID', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='fees.feeinvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
