# Generated by Django 6.0.3 on 2026-04-15 12:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('finance', '0015_account_available_in_payroll'),
        ('journals', '0001_initial'),
        ('payables', '0011_allow_liability_accounts_on_gl_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gl_expense_account', models.ForeignKey(blank=True, help_text='Default expense GL account for items in this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_categories', to='finance.account')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceivedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(max_length=30, unique=True)),
                ('received_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('POSTED', 'Posted to GL')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grns', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns', to='journals.journalentry')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_grns', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='payables.supplier')),
                ('supplier_invoice', models.ForeignKey(blank=True, help_text='Link to supplier invoice for 3-way matching', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns', to='payables.supplierinvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Auto-generated if blank', max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('CONSUMABLE', 'Consumable'), ('CAPITAL_ASSET', 'Capital Asset'), ('RAW_MATERIAL', 'Raw Material')], default='CONSUMABLE', max_length=20)),
                ('unit_of_measure', models.CharField(choices=[('Pcs', 'Pieces'), ('Box', 'Box'), ('Ream', 'Ream'), ('Bale', 'Bale'), ('Unit', 'Unit'), ('Kg', 'Kilograms'), ('Liters', 'Liters'), ('Meters', 'Meters'), ('Jerrican', 'Jerrican'), ('Pack', 'Pack'), ('Roll', 'Roll'), ('Set', 'Set'), ('Pair', 'Pair'), ('Carton', 'Carton'), ('Bottle', 'Bottle'), ('Dozen', 'Dozen')], default='Pcs', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('min_level', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum stock level before reorder alert', max_digits=15)),
                ('reorder_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suggested quantity to reorder', max_digits=15)),
                ('location', models.CharField(blank=True, help_text='e.g. Store A-12', max_length=100, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired'), ('DISPOSED', 'Disposed')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_items', to=settings.AUTH_USER_MODEL)),
                ('gl_asset_account', models.ForeignKey(blank=True, help_text='Inventory asset account (BS)', limit_choices_to={'sub_type': 'INVENTORY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_asset_items', to='finance.account')),
                ('gl_expense_account', models.ForeignKey(blank=True, help_text='Expense account for consumption (P&L)', limit_choices_to={'type': 'EXPENSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_expense_items', to='finance.account')),
                ('supplier', models.ForeignKey(blank=True, help_text='Default/primary supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='payables.supplier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GRNLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.goodsreceivednote')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_lines', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Receipt (GRN)'), ('ISSUE', 'Issue (Supply Voucher)'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('RETURN', 'Return'), ('WRITE_OFF', 'Write Off'), ('OPENING', 'Opening Balance')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryitem')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='journals.journalentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_takes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SupplyIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(max_length=30, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('requested_by', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('ISSUED', 'Issued'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_issues', to=settings.AUTH_USER_MODEL)),
                ('budget_line', models.ForeignKey(blank=True, help_text='Budget line for consumption tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_issues', to='budgets.budgetline')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_issues', to='journals.journalentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyIssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity_issued', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.supplyissue')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_items', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockTakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('physical_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('variance_reason', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_take_lines', to='inventory.inventoryitem')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktake')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('stock_take', 'item')},
            },
        ),
    ]
