# Generated by Django 6.0.3 on 2026-07-27 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0002_initial'),
        ('finance', '0001_initial'),
        ('inventory', '0001_initial'),
        ('journals', '0001_initial'),
        ('payables', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Link to purchase order for 3-way matching', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_grns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='payables.supplier'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='supplier_invoice',
            field=models.ForeignKey(blank=True, help_text='Link to supplier invoice for 3-way matching', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns', to='payables.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='grnline',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.goodsreceivednote'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.category'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='gl_asset_account',
            field=models.ForeignKey(blank=True, help_text='Inventory asset account (BS)', limit_choices_to={'sub_type': 'INVENTORY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_asset_items', to='finance.account'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='gl_expense_account',
            field=models.ForeignKey(blank=True, help_text='Expense account for consumption (P&L)', limit_choices_to={'type': 'EXPENSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_expense_items', to='finance.account'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Default/primary supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='payables.supplier'),
        ),
        migrations.AddField(
            model_name='grnline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_lines', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='journals.journalentry'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='conducted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_takes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktakeline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_take_lines', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='stocktakeline',
            name='stock_take',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktake'),
        ),
        migrations.AddField(
            model_name='supplyissue',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplyissue',
            name='budget_line',
            field=models.ForeignKey(blank=True, help_text='Budget line for consumption tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_issues', to='budgets.budgetline'),
        ),
        migrations.AddField(
            model_name='supplyissue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplyissue',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_issues', to='journals.journalentry'),
        ),
        migrations.AddField(
            model_name='supplyissueitem',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.supplyissue'),
        ),
        migrations.AddField(
            model_name='supplyissueitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_items', to='inventory.inventoryitem'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktakeline',
            unique_together={('stock_take', 'item')},
        ),
    ]
