# Generated by Django 6.0.3 on 2026-04-20 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceivednote",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to purchase order for 3-way matching",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grns",
                to="procurement.purchaseorder",
            ),
        ),
    ]
