# Generated by Django 6.0.3 on 2026-08-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='student_set_student_24b25c_idx',
            old_name='student_enr_student_f98c50_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='student_set_status_05f2ad_idx',
            old_name='student_enr_status_cda505_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='student_set_enrollm_4d31bc_idx',
            old_name='student_enr_enrollm_9a4379_idx',
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table=None,
        ),
    ]
