# Generated by Django 5.2.7 on 2025-12-17 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discipline', models.CharField(help_text='STEM, Education, Business, Arts, etc.', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('accreditation_body', models.CharField(blank=True, max_length=255)),
                ('is_accredited', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='is_academic',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProfessionalCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=255)),
                ('issuing_body', models.CharField(max_length=255)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='employee/certifications/')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='workforce.employee')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_certifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContinuousProfessionalDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('cpd_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='employee/cpd/')),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cpd', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpd_records', to='workforce.employee')),
                ('linked_certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpd_activities', to='workforce.professionalcertification')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_title', models.CharField(max_length=255)),
                ('graduation_date', models.DateField()),
                ('classification', models.CharField(blank=True, help_text='First Class, Second Upper, GPA, etc.', max_length=100)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='employee/education/')),
                ('verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='education_level', to='workforce.educationlevel')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='workforce.employee')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_educations', to=settings.AUTH_USER_MODEL)),
                ('field_of_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.fieldofstudy')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workforce.institution')),
            ],
            options={
                'ordering': ['-graduation_date'],
                'unique_together': {('employee', 'education_level', 'institution')},
            },
        ),
    ]
