# Generated by Django 6.0.1 on 2026-01-23 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_fieldofstudy_institution_educationlevel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workforce.campus'),
        ),
        migrations.AlterField(
            model_name='department',
            name='cost_center_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('academic', 'Academic'), ('administrative', 'Administrative'), ('support', 'Support Services')], default='administrative', max_length=20),
        ),
    ]
