# Generated by Django 6.0.1 on 2026-01-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0003_alter_department_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeearning',
            name='calculation_basis',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('hours', 'Hours Worked'), ('rate', 'Rate Ã— Units'), ('percentage', 'Percentage')], max_length=20),
        ),
    ]
