# Generated by Django 6.0.2 on 2026-03-04 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workforce", "0005_employee_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="contract_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="contract_renewal_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employee",
            name="contract_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="exit_interview_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="exit_interview_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_system_user",
            field=models.BooleanField(default=True, help_text="Has login credentials"),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_profile_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_promotion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_working_day",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="notice_period_days",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="employee",
            name="number_of_dependents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employee",
            name="probation_end_date",
            field=models.DateField(
                blank=True, help_text="Expected end date of probation period", null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="probation_period_months",
            field=models.PositiveIntegerField(
                default=3, help_text="Duration of probation in months"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="profile_completion_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employee",
            name="rehire_eligible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="rehire_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="resignation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="resignation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="spouse_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="employee",
            name="termination_reason",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="BulkImportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("employees", "Employees"),
                            ("departments", "Departments"),
                            ("positions", "Positions"),
                            ("attendance", "Attendance"),
                            ("leave_balances", "Leave Balances"),
                            ("job_titles", "Job Titles"),
                            ("job_grades", "Job Grades"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("validating", "Validating"),
                            ("validated", "Validated"),
                            ("validation_failed", "Validation Failed"),
                            ("preview", "Ready for Preview"),
                            ("importing", "Importing"),
                            ("completed", "Completed"),
                            ("partially_completed", "Partially Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="uploaded",
                        max_length=30,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("uploaded_file", models.FileField(upload_to="bulk_imports/%Y/%m/")),
                ("file_size_bytes", models.PositiveIntegerField()),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("error_rows", models.PositiveIntegerField(default=0)),
                ("warning_rows", models.PositiveIntegerField(default=0)),
                ("imported_rows", models.PositiveIntegerField(default=0)),
                ("skipped_rows", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("validation_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "validation_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("import_started_at", models.DateTimeField(blank=True, null=True)),
                ("import_completed_at", models.DateTimeField(blank=True, null=True)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("error_summary", models.TextField(blank=True)),
                (
                    "error_file",
                    models.FileField(
                        blank=True, upload_to="bulk_imports/errors/%Y/%m/"
                    ),
                ),
                (
                    "skip_duplicates",
                    models.BooleanField(
                        default=True, help_text="Skip rows with duplicate identifiers"
                    ),
                ),
                (
                    "update_existing",
                    models.BooleanField(
                        default=False,
                        help_text="Update existing records instead of skipping",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_bulk_import_session",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="BulkImportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("raw_data", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Validation"),
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("warning", "Valid with Warnings"),
                            ("imported", "Imported"),
                            ("skipped", "Skipped"),
                            ("failed", "Import Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("validation_warnings", models.JSONField(blank=True, default=list)),
                ("processed_data", models.JSONField(blank=True, null=True)),
                (
                    "created_employee_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_object_type", models.CharField(blank=True, max_length=50)),
                (
                    "created_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "import_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="workforce.bulkimportsession",
                    ),
                ),
            ],
            options={
                "db_table": "hr_bulk_import_record",
                "ordering": ["row_number"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_name", models.CharField(max_length=255)),
                (
                    "document_category",
                    models.CharField(
                        choices=[
                            ("identification", "Identification"),
                            ("education", "Education"),
                            ("employment", "Employment"),
                            ("certification", "Certification"),
                            ("medical", "Medical"),
                            ("legal", "Legal"),
                            ("contract", "Contract"),
                            ("performance", "Performance"),
                            ("disciplinary", "Disciplinary"),
                            ("financial", "Financial"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        help_text="e.g., Passport, Degree Certificate, Contract",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="employee_documents/%Y/%m/")),
                ("file_size_bytes", models.PositiveIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Passport Number, Certificate Number",
                        max_length=100,
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("issuing_authority", models.CharField(blank=True, max_length=255)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verification_date", models.DateField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "is_confidential",
                    models.BooleanField(
                        default=False, help_text="Only HR admins can view"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expiry_alert_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Days before expiry to send alert"
                    ),
                ),
                ("expiry_alert_sent", models.BooleanField(default=False)),
                ("expiry_alert_sent_date", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="workforce.employee",
                    ),
                ),
                (
                    "issuing_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_documents",
                        to="workforce.country",
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newer_versions",
                        to="workforce.employeedocument",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_employee_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_employee_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HRAutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[
                            ("probation_ending", "Probation Ending Soon"),
                            ("contract_ending", "Contract Ending Soon"),
                            ("document_expiring", "Document Expiring"),
                            ("birthday", "Employee Birthday"),
                            ("work_anniversary", "Work Anniversary"),
                            ("appraisal_due", "Appraisal Due"),
                            ("leave_balance_low", "Leave Balance Low"),
                            ("new_hire_onboarding", "New Hire Onboarding"),
                            ("status_change", "Employment Status Change"),
                            ("certification_expiring", "Certification Expiring"),
                            ("attendance_threshold", "Attendance Threshold"),
                            ("leave_request_pending", "Leave Request Pending"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "trigger_conditions",
                    models.JSONField(
                        default=dict, help_text="Additional conditions in JSON format"
                    ),
                ),
                (
                    "trigger_days_before",
                    models.PositiveIntegerField(
                        default=7, help_text="Days before event to trigger"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("send_email", "Send Email"),
                            ("send_notification", "Send In-App Notification"),
                            ("create_task", "Create Task"),
                            ("update_status", "Update Status"),
                            ("trigger_workflow", "Trigger Workflow"),
                            ("send_sms", "Send SMS"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "action_config",
                    models.JSONField(
                        default=dict, help_text="Action configuration in JSON format"
                    ),
                ),
                ("notify_employee", models.BooleanField(default=True)),
                ("notify_supervisor", models.BooleanField(default=False)),
                ("notify_hr", models.BooleanField(default=True)),
                ("notify_department_head", models.BooleanField(default=False)),
                (
                    "additional_recipients",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of email addresses or user IDs",
                    ),
                ),
                ("email_subject", models.CharField(blank=True, max_length=255)),
                (
                    "email_body_template",
                    models.TextField(
                        blank=True,
                        help_text="Supports placeholders: {employee_name}, {event_date}, etc.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "run_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("run_count", models.PositiveIntegerField(default=0)),
                (
                    "applies_to_employee_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of employee categories: teaching, non_teaching, etc.",
                    ),
                ),
                (
                    "applies_to_departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to apply to all departments",
                        related_name="automation_rules",
                        to="workforce.department",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_automation_rule",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HRAutomationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("trigger_reason", models.CharField(max_length=255)),
                ("action_taken", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("partial", "Partial Success"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("recipients_notified", models.JSONField(blank=True, default=list)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "context_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context about the trigger",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_logs",
                        to="workforce.employee",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="workforce.hrautomationrule",
                    ),
                ),
            ],
            options={
                "db_table": "hr_automation_log",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="HRNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_probation_reminders", models.BooleanField(default=True)),
                ("email_contract_reminders", models.BooleanField(default=True)),
                ("email_document_expiry", models.BooleanField(default=True)),
                ("email_leave_requests", models.BooleanField(default=True)),
                ("email_appraisal_reminders", models.BooleanField(default=True)),
                ("email_birthday_wishes", models.BooleanField(default=True)),
                ("email_work_anniversary", models.BooleanField(default=True)),
                ("app_probation_reminders", models.BooleanField(default=True)),
                ("app_contract_reminders", models.BooleanField(default=True)),
                ("app_document_expiry", models.BooleanField(default=True)),
                ("app_leave_requests", models.BooleanField(default=True)),
                ("app_appraisal_reminders", models.BooleanField(default=True)),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("daily", "Daily Digest"),
                            ("weekly", "Weekly Digest"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_notification_preference",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position_code", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("contract", "Contract"),
                            ("temporary", "Temporary"),
                            ("grant_funded", "Grant Funded"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "funding_status",
                    models.CharField(
                        choices=[
                            ("funded", "Funded"),
                            ("unfunded", "Unfunded"),
                            ("frozen", "Frozen"),
                        ],
                        default="funded",
                        max_length=20,
                    ),
                ),
                (
                    "vacancy_status",
                    models.CharField(
                        choices=[
                            ("vacant", "Vacant"),
                            ("occupied", "Occupied"),
                            ("on_hold", "On Hold"),
                        ],
                        default="vacant",
                        max_length=20,
                    ),
                ),
                (
                    "budgeted_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("budget_code", models.CharField(blank=True, max_length=50)),
                ("fiscal_year", models.PositiveIntegerField(blank=True, null=True)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text="Key position requiring succession plan",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="workforce.campus",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="held_positions",
                        to="workforce.employee",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="workforce.department",
                    ),
                ),
                (
                    "job_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="workforce.jobtitle",
                    ),
                ),
                (
                    "reports_to_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinate_positions",
                        to="workforce.position",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_position",
                "ordering": ["department", "position_code"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeLifecycleLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("hired", "Hired"),
                            ("promotion", "Promotion"),
                            ("transfer", "Transfer"),
                            ("demotion", "Demotion"),
                            ("salary_change", "Salary Change"),
                            ("status_change", "Status Change"),
                            ("probation_confirmed", "Probation Confirmed"),
                            ("probation_extended", "Probation Extended"),
                            ("suspended", "Suspended"),
                            ("reinstated", "Reinstated"),
                            ("resigned", "Resigned"),
                            ("terminated", "Terminated"),
                            ("retired", "Retired"),
                            ("contract_renewed", "Contract Renewed"),
                            ("contract_ended", "Contract Ended"),
                            ("position_assigned", "Position Assigned"),
                            ("department_changed", "Department Changed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("event_date", models.DateField()),
                ("effective_date", models.DateField()),
                ("old_status", models.CharField(blank=True, max_length=50)),
                ("new_status", models.CharField(max_length=50)),
                (
                    "old_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "new_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "supporting_document",
                    models.FileField(blank=True, upload_to="lifecycle_docs/%Y/%m/"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="e.g., termination letter number",
                        max_length=100,
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional event-specific data",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_lifecycle_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifecycle_logs",
                        to="workforce.employee",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_lifecycle_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lifecycle_logs_new_dept",
                        to="workforce.department",
                    ),
                ),
                (
                    "new_job_grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lifecycle_logs_new_grade",
                        to="workforce.jobgrade",
                    ),
                ),
                (
                    "old_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lifecycle_logs_old_dept",
                        to="workforce.department",
                    ),
                ),
                (
                    "old_job_grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lifecycle_logs_old_grade",
                        to="workforce.jobgrade",
                    ),
                ),
                (
                    "new_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lifecycle_logs_new_pos",
                        to="workforce.position",
                    ),
                ),
                (
                    "old_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lifecycle_logs_old_pos",
                        to="workforce.position",
                    ),
                ),
            ],
            options={
                "db_table": "hr_employee_lifecycle_log",
                "ordering": ["-event_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="bulkimportsession",
            index=models.Index(fields=["status"], name="hr_bulk_imp_status_254c96_idx"),
        ),
        migrations.AddIndex(
            model_name="bulkimportsession",
            index=models.Index(
                fields=["import_type", "status"], name="hr_bulk_imp_import__3b24f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulkimportsession",
            index=models.Index(
                fields=["uploaded_at"], name="hr_bulk_imp_uploade_81b829_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulkimportrecord",
            index=models.Index(
                fields=["import_session", "status"],
                name="hr_bulk_imp_import__df8e9c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bulkimportrecord",
            unique_together={("import_session", "row_number")},
        ),
        migrations.AddIndex(
            model_name="employeedocument",
            index=models.Index(
                fields=["employee", "document_category"],
                name="hr_employee_employe_e470e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employeedocument",
            index=models.Index(
                fields=["expiry_date"], name="hr_employee_expiry__91aa6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeedocument",
            index=models.Index(
                fields=["verification_status"], name="hr_employee_verific_ade39b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeedocument",
            index=models.Index(
                fields=["document_category"], name="hr_employee_documen_99b7b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrautomationrule",
            index=models.Index(
                fields=["trigger_event", "is_active"],
                name="hr_automati_trigger_463cda_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hrautomationrule",
            index=models.Index(
                fields=["is_active"], name="hr_automati_is_acti_a540fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrautomationlog",
            index=models.Index(
                fields=["rule", "triggered_at"], name="hr_automati_rule_id_44feae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrautomationlog",
            index=models.Index(
                fields=["employee", "triggered_at"],
                name="hr_automati_employe_bc8d46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hrautomationlog",
            index=models.Index(fields=["status"], name="hr_automati_status_f2ec6e_idx"),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["department", "vacancy_status"],
                name="hr_position_departm_81e8e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["position_code"], name="hr_position_positio_404964_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["vacancy_status"], name="hr_position_vacancy_77459a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["funding_status"], name="hr_position_funding_a32003_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeelifecyclelog",
            index=models.Index(
                fields=["employee", "event_type"], name="hr_employee_employe_a52028_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeelifecyclelog",
            index=models.Index(
                fields=["event_date"], name="hr_employee_event_d_71d910_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeelifecyclelog",
            index=models.Index(
                fields=["event_type"], name="hr_employee_event_t_084e37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeelifecyclelog",
            index=models.Index(
                fields=["effective_date"], name="hr_employee_effecti_81f996_idx"
            ),
        ),
    ]
