# Generated by Django 6.0.2 on 2026-03-04 17:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workforce", "0006_employee_blood_group_employee_contract_end_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalWorkflowLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("level_number", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "approver_role",
                    models.CharField(
                        help_text="Role name that can approve at this level",
                        max_length=100,
                    ),
                ),
                ("can_approve", models.BooleanField(default=True)),
                ("can_reject", models.BooleanField(default=True)),
                ("can_request_changes", models.BooleanField(default=True)),
                ("notify_on_pending", models.BooleanField(default=True)),
                (
                    "auto_escalate_hours",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Hours before auto-escalating to next level",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_approval_workflow",
                "ordering": ["level_number"],
            },
        ),
        migrations.CreateModel(
            name="GLAccountMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mapping_type",
                    models.CharField(
                        choices=[
                            ("salary_expense", "Gross Salary Expense"),
                            ("paye_liability", "PAYE Payable"),
                            ("nssf_liability", "NSSF Payable"),
                            ("nhif_liability", "NHIF/SHIF Payable"),
                            ("housing_levy", "Housing Levy Payable"),
                            ("pension_liability", "Pension Payable"),
                            ("net_pay_liability", "Net Salary Payable"),
                            ("bank_account", "Payroll Bank Account"),
                            ("allowance_expense", "Allowances Expense"),
                            ("overtime_expense", "Overtime Expense"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("gl_account_code", models.CharField(max_length=50)),
                ("gl_account_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_gl_mapping",
            },
        ),
        migrations.CreateModel(
            name="PayrollConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pay_frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("bi_weekly", "Bi-Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "payroll_run_date",
                    models.PositiveSmallIntegerField(
                        default=25, help_text="Day of month when payroll is processed"
                    ),
                ),
                (
                    "attendance_cutoff_date",
                    models.PositiveSmallIntegerField(
                        default=20,
                        help_text="Last day for including attendance/OT in current cycle",
                    ),
                ),
                (
                    "financial_year_start",
                    models.CharField(
                        choices=[
                            ("january", "January (Calendar Year)"),
                            ("april", "April (UK/India)"),
                            ("july", "July (East Africa)"),
                            ("october", "October (US Federal)"),
                        ],
                        default="july",
                        max_length=20,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Lock prevents all payroll changes"
                    ),
                ),
                ("currency_code", models.CharField(default="KES", max_length=3)),
                (
                    "rounding_method",
                    models.CharField(
                        choices=[
                            ("none", "No Rounding (Exact)"),
                            ("nearest", "Nearest Whole Number"),
                            ("up_10", "Round Up to Nearest 10"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "overtime_multiplier",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("1.5"), max_digits=3
                    ),
                ),
                (
                    "holiday_multiplier",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("2.0"), max_digits=3
                    ),
                ),
                (
                    "enable_proration",
                    models.BooleanField(
                        default=True,
                        help_text="Auto-calculate for mid-month joiners/leavers",
                    ),
                ),
                ("require_2fa_approval", models.BooleanField(default=False)),
                ("allow_retroactive_changes", models.BooleanField(default=False)),
                ("audit_retention_years", models.PositiveSmallIntegerField(default=7)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Configuration",
                "db_table": "payroll_configuration",
            },
        ),
        migrations.CreateModel(
            name="StatutoryRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("nssf_tier1", "NSSF Tier I"),
                            ("nssf_tier2", "NSSF Tier II"),
                            ("shif", "Social Health Insurance Fund"),
                            ("nhif", "NHIF (Legacy)"),
                            ("housing_levy", "Affordable Housing Levy"),
                            ("nita", "NITA Levy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "employee_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Employee contribution %",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "employer_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Employer contribution %",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fixed amount if not percentage-based",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "lower_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Income threshold for this tier",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "upper_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_contribution",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum contribution cap",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this deduction is applied in calculations",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_statutory_rate",
                "ordering": ["rate_type", "effective_date"],
            },
        ),
        migrations.CreateModel(
            name="TaxBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lower_limit", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "upper_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank for top band (no upper limit)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tax rate as percentage (e.g., 30.00)",
                        max_digits=5,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(help_text="Date from which this band applies"),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if currently active",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_tax_band",
                "ordering": ["effective_date", "sort_order", "lower_limit"],
            },
        ),
        migrations.CreateModel(
            name="TaxRelief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relief_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Relief"),
                            ("insurance", "Insurance Relief"),
                            ("housing", "Affordable Housing Relief"),
                            ("pension", "Pension Relief"),
                            ("disability", "Disability Relief"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fixed monthly relief amount",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Relief as % of contribution",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum relief cap",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_tax_relief",
            },
        ),
    ]
