# Generated by Django 6.0.3 on 2026-04-09 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_institution_to_campus"),
        ("workforce", "0007_approvalworkflowlevel_glaccountmapping_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campus",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="campus",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="campus",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="campus",
            name="county",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="campus",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="campus",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                help_text="The institution this campus belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campuses",
                to="core.institutionprofile",
            ),
        ),
        migrations.AddField(
            model_name="campus",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="campus",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="campus",
            name="principal_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
