# Generated by Django 6.0.3 on 2026-04-09 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0008_add_institution_to_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='workforce.campus'),
        ),
    ]
