# Generated by Django 6.0.3 on 2026-04-11 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_account_available_in_payroll'),
        ('workforce', '0009_employee_campus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeededuction',
            name='deduction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workforce.deductiontype'),
        ),
        migrations.AlterField(
            model_name='employeeearning',
            name='earning_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workforce.earningtype'),
        ),
        migrations.CreateModel(
            name='PayGradeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_number', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Salary amount at this step', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('job_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workforce.jobgrade')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_pay_grade_step',
                'ordering': ['job_grade', 'step_number'],
                'unique_together': {('job_grade', 'step_number')},
            },
        ),
        migrations.AddField(
            model_name='employeepayprofile',
            name='pay_grade_step',
            field=models.ForeignKey(blank=True, help_text='If set, basic_salary is derived from step amount', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profiles', to='workforce.paygradestep'),
        ),
        migrations.CreateModel(
            name='PayrollAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=20)),
                ('category', models.CharField(choices=[('basic', 'Basic Salary'), ('allowance', 'Allowance'), ('bonus', 'Bonus'), ('overtime', 'Overtime'), ('commission', 'Commission'), ('arrears', 'Arrears'), ('statutory', 'Statutory'), ('voluntary', 'Voluntary'), ('loan', 'Loan Repayment'), ('advance', 'Advance Recovery'), ('penalty', 'Penalty')], max_length=20)),
                ('has_employer_contribution', models.BooleanField(default=False, help_text='Does this account have an employer-side contribution?')),
                ('used_for_paye', models.BooleanField(default=False, help_text='Include this earning in PAYE taxable income calculation')),
                ('used_for_nhif_shif', models.BooleanField(default=False, help_text='Include this earning in NHIF/SHIF contribution base')),
                ('used_for_pension', models.BooleanField(default=False, help_text='Include this earning in pension/NSSF contribution base')),
                ('is_allowable_deduction', models.BooleanField(default=False, help_text='Deduction that reduces taxable income before PAYE')),
                ('used_for_housing_levy', models.BooleanField(default=False, help_text='This is the housing levy deduction')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Automatically applied to all eligible employees')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee_gl_account', models.ForeignKey(help_text='GL account for employee portion', limit_choices_to={'available_in_payroll': True}, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_accounts_employee', to='finance.account')),
                ('employer_gl_account', models.ForeignKey(blank=True, help_text='GL account for employer portion', limit_choices_to={'available_in_payroll': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_accounts_employer', to='finance.account')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_account',
                'ordering': ['account_type', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='payroll_account',
            field=models.ForeignKey(blank=True, help_text="Select from payroll accounts of type 'deduction'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_deductions', to='workforce.payrollaccount'),
        ),
        migrations.AddField(
            model_name='employeeearning',
            name='payroll_account',
            field=models.ForeignKey(blank=True, help_text="Select from payroll accounts of type 'earning'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_earnings', to='workforce.payrollaccount'),
        ),
        migrations.AddField(
            model_name='statutoryrate',
            name='payroll_account',
            field=models.ForeignKey(blank=True, help_text='Payroll account (deduction type) linked to this statutory item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statutory_rates', to='workforce.payrollaccount'),
        ),
    ]
