# Generated by Django 6.0.3 on 2026-04-11 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0010_alter_employeededuction_deduction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepayprofile',
            name='pay_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workforce.payprofile'),
        ),
    ]
