# Generated by Django 6.0.3 on 2026-04-13 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0012_paysliptemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculation_method', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage_of_gross', 'Percentage of Gross'), ('percentage_of_basic', 'Percentage of Basic')], default='fixed', max_length=30)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Only used when calculation_method is percentage-based', max_digits=5, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('job_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_deductions', to='workforce.jobgrade')),
                ('payroll_account', models.ForeignKey(limit_choices_to={'account_type': 'deduction'}, on_delete=django.db.models.deletion.PROTECT, related_name='group_deductions', to='workforce.payrollaccount')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_group_deduction',
                'ordering': ['job_grade', 'payroll_account__sort_order'],
                'unique_together': {('job_grade', 'payroll_account')},
            },
        ),
        migrations.CreateModel(
            name='GroupEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('job_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_earnings', to='workforce.jobgrade')),
                ('payroll_account', models.ForeignKey(limit_choices_to={'account_type': 'earning'}, on_delete=django.db.models.deletion.PROTECT, related_name='group_earnings', to='workforce.payrollaccount')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_group_earning',
                'ordering': ['job_grade', 'payroll_account__sort_order'],
                'unique_together': {('job_grade', 'payroll_account')},
            },
        ),
    ]
