# Generated by Django 6.0.3 on 2026-04-13 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workforce", "0013_add_group_earnings_deductions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PensionScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "scheme_type",
                    models.CharField(
                        choices=[
                            ("ipp", "Individual Pension Plan"),
                            ("occupational", "Occupational Scheme"),
                            ("nssf", "NSSF"),
                            ("custom", "Custom"),
                        ],
                        default="ipp",
                        max_length=20,
                    ),
                ),
                ("provider_name", models.CharField(blank=True, max_length=200)),
                (
                    "provider_account_number",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "employee_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Default employee contribution rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "employer_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Default employer contribution rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "max_employee_contribution",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly cap on employee contribution",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "max_employer_contribution",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly cap on employer contribution",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "calculation_basis",
                    models.CharField(
                        choices=[
                            ("basic_salary", "Basic Salary"),
                            ("gross_pay", "Gross Pay"),
                            ("fixed_amount", "Fixed Amount"),
                        ],
                        default="basic_salary",
                        max_length=20,
                    ),
                ),
                (
                    "is_tax_exempt",
                    models.BooleanField(
                        default=True,
                        help_text="Whether contributions qualify for tax relief",
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payroll_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Payroll account for GL mapping",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pension_schemes",
                        to="workforce.payrollaccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_pension_scheme",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeePensionEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membership_number",
                    models.CharField(
                        blank=True,
                        help_text="External pension member ID",
                        max_length=100,
                    ),
                ),
                (
                    "employee_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Individual employee rate override (%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "employer_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Individual employer rate override (%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "custom_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fixed amount override (when basis is fixed_amount)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("enrollment_date", models.DateField()),
                ("exit_date", models.DateField(blank=True, null=True)),
                ("exit_reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("exited", "Exited"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pension_enrollments",
                        to="workforce.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pension_scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="workforce.pensionscheme",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_pension_enrollment",
                "ordering": ["-enrollment_date"],
                "unique_together": {("employee", "pension_scheme")},
            },
        ),
        migrations.CreateModel(
            name="PensionContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "employer_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "employee_rate_applied",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rate that was applied for this period",
                        max_digits=5,
                    ),
                ),
                (
                    "employer_rate_applied",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rate that was applied for this period",
                        max_digits=5,
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The salary base used for calculation",
                        max_digits=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="workforce.employeepensionenrollment",
                    ),
                ),
                (
                    "payroll_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pension_contributions",
                        to="workforce.payrollperiod",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_pension_contribution",
                "ordering": ["-payroll_period__start_date"],
                "unique_together": {("enrollment", "payroll_period")},
            },
        ),
        migrations.CreateModel(
            name="PensionSchemeGradeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Employee contribution rate (%) for this grade",
                        max_digits=5,
                    ),
                ),
                (
                    "employer_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Employer contribution rate (%) for this grade",
                        max_digits=5,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pension_grade_rates",
                        to="workforce.jobgrade",
                    ),
                ),
                (
                    "pension_scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_rates",
                        to="workforce.pensionscheme",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_pension_grade_rate",
                "ordering": ["pension_scheme", "job_grade"],
                "unique_together": {("pension_scheme", "job_grade")},
            },
        ),
    ]
