# Generated by Django 6.0.3 on 2026-04-13 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workforce", "0014_add_pension_scheme_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollcalculationdetail",
            name="payroll_account",
            field=models.ForeignKey(
                blank=True,
                help_text="PayrollAccount used for this line item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calculation_details",
                to="workforce.payrollaccount",
            ),
        ),
    ]
