# Generated by Django 6.0.3 on 2026-04-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0015_add_payroll_account_to_calculation_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollperiod',
            options={'ordering': ['-start_date'], 'permissions': [('can_unlock_payroll_period', 'Can unlock payroll period for re-run')]},
        ),
    ]
