# Generated by Django 6.0.3 on 2026-04-23 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workforce", "0016_add_can_unlock_payroll_period_permission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancepolicy",
            name="allow_biometric_clock_in",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="allow_geolocation_clock_in",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="allow_remote_clock_in",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="default_geofence_radius_meters",
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="require_on_site_geofence",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campus",
            name="geofence_radius_meters",
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name="campus",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="campus",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="check_in_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("biometric", "Biometric"),
                    ("geolocation", "On-Site Geolocation"),
                    ("remote", "Remote"),
                    ("manual", "Manual Entry"),
                    ("mobile", "Mobile App"),
                    ("system", "System Generated"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="check_out_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("biometric", "Biometric"),
                    ("geolocation", "On-Site Geolocation"),
                    ("remote", "Remote"),
                    ("manual", "Manual Entry"),
                    ("mobile", "Mobile App"),
                    ("system", "System Generated"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="EmployeeAttendanceAccessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enforce_biometric", models.BooleanField(blank=True, null=True)),
                ("allow_remote_clock_in", models.BooleanField(blank=True, null=True)),
                (
                    "allow_geolocation_clock_in",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "require_on_site_geofence",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "geofence_radius_meters",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_campus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_profiles",
                        to="workforce.campus",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_access_profile",
                        to="workforce.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Employee Attendance Access Profiles",
                "db_table": "hr_employee_attendance_access_profile",
            },
        ),
    ]
