# Generated by Django 6.0.3 on 2026-06-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workforce", "0018_employeeperformancegoal"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupearning",
            name="calculation_method",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed Amount"),
                    ("percentage_of_basic", "Percentage of Basic"),
                ],
                default="fixed",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="groupearning",
            name="percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Only used when calculation_method is percentage-based",
                max_digits=5,
                null=True,
            ),
        ),
    ]
