# Generated by Django 6.0.3 on 2026-08-15 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_management', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('middle_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=60, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_parent_guardian',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentCommunicationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_enabled', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('portal_notifications_enabled', models.BooleanField(default=True)),
                ('preferred_channel', models.CharField(default='whatsapp', max_length=20)),
                ('marketing_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_preferences', to='crm.parentguardian')),
            ],
            options={
                'db_table': 'crm_parent_communication_preference',
            },
        ),
        migrations.CreateModel(
            name='ParentStudentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=50)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('can_receive_academic_updates', models.BooleanField(default=True)),
                ('can_receive_financial_updates', models.BooleanField(default=False)),
                ('can_receive_attendance_updates', models.BooleanField(default=True)),
                ('can_receive_disciplinary_updates', models.BooleanField(default=True)),
                ('can_receive_general_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='crm.parentguardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_parents', to='student_management.student')),
            ],
            options={
                'db_table': 'crm_parent_student_relationship',
                'unique_together': {('parent', 'student')},
            },
        ),
    ]
