# Generated by Django 6.0.3 on 2026-08-15 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('student_management', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('FEES', 'Fees'), ('ATTENDANCE', 'Attendance'), ('EXAMINATION', 'Examination'), ('DISCIPLINE', 'Discipline'), ('ADMISSION', 'Admission'), ('GENERAL', 'General Announcement')], default='GENERAL', max_length=50)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crm_communication_template',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('last_outbound_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='crm.parentguardian')),
            ],
            options={
                'db_table': 'crm_conversation',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='GENERAL', max_length=50)),
                ('channel', models.CharField(max_length=20)),
                ('direction', models.CharField(default='OUTBOUND', max_length=10)),
                ('message_body', models.TextField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=120, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recipient_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='crm.parentguardian')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_communications', to='student_management.student')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.communicationtemplate')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='crm.conversation')),
            ],
            options={
                'db_table': 'crm_communication',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=10)),
                ('body', models.TextField()),
                ('provider_message_id', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.conversation')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_conversation_message',
                'ordering': ['sent_at'],
            },
        ),
    ]
