# Generated by Django 6.0.3 on 2026-08-15 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_communicationtemplate_conversation_communication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default='GENERAL', max_length=50)),
                ('channel', models.CharField(max_length=20)),
                ('audience_filters', models.JSONField(default=dict)),
                ('custom_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.communicationtemplate')),
            ],
            options={
                'db_table': 'crm_campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_phone', models.CharField(max_length=60)),
                ('context_data', models.JSONField(default=dict)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=120, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='crm.campaign')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.parentguardian')),
            ],
            options={
                'db_table': 'crm_campaign_recipient',
                'unique_together': {('campaign', 'parent')},
            },
        ),
    ]
