# Generated by Django 6.0.3 on 2026-08-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_campaign_campaignrecipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('twilio', 'Twilio (WhatsApp/SMS)'), ('africastalking', "Africa's Talking (SMS)")], max_length=50, unique=True)),
                ('account_id', models.CharField(blank=True, help_text='Twilio Account SID or AT Username', max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, help_text='Twilio Auth Token or AT API Key', max_length=255, null=True)),
                ('sender_id', models.CharField(blank=True, help_text='Twilio Phone Number or AT Sender ID', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this provider')),
                ('use_mock', models.BooleanField(default=False, help_text='Use mock sending for testing/development without using credits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider Configuration',
                'verbose_name_plural': 'Provider Configurations',
                'db_table': 'crm_provider_config',
            },
        ),
    ]
