# Generated by Django 6.0.3 on 2026-08-15 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data_scope_queried', models.CharField(max_length=255)),
                ('document_type_generated', models.CharField(max_length=100)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DISCARDED', 'Discarded')], default='PENDING', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intelligence_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('documents_generated', models.IntegerField(default=0)),
                ('tokens_approx', models.IntegerField(default=0)),
                ('cost_approx', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'intelligence_usage',
                'ordering': ['-month'],
                'unique_together': {('month',)},
            },
        ),
    ]
