# Generated by Django 6.0.3 on 2026-08-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnthropicAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A name to identify this key, e.g. 'Production Key'", max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anthropic API Key',
                'verbose_name_plural': 'Anthropic API Keys',
                'db_table': 'anthropic_api_key',
                'ordering': ['-created_at'],
            },
        ),
    ]
