# Generated by Django 6.0.2 on 2026-02-27 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('student_settings', '0008_enrollment_reporting_reason_enrollment_stay_status'),
        ('workforce', '0005_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('lab', 'Laboratory'), ('hall', 'Assembly Hall / Multipurpose'), ('library', 'Library'), ('field', 'Sports Field / Outdoor'), ('online', 'Online / Virtual')], default='classroom', max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=40)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='workforce.campus')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('color_hex', models.CharField(default='#6366f1', help_text='UI colour code for timetable and dashboard display.', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='student_settings.curriculum')),
                ('curriculum_level', models.ForeignKey(blank=True, help_text='If null, subject applies to all levels of the curriculum.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='student_settings.curriculumlevel')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('planned_lessons', models.PositiveSmallIntegerField(default=1, help_text='Expected number of lessons needed to complete this unit.')),
                ('sequence_order', models.PositiveSmallIntegerField(default=1, help_text='Order in which this unit should be taught.')),
                ('is_compulsory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_units', to='academics.classsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_units', to='timetable.subject')),
            ],
            options={
                'verbose_name': 'Curriculum Unit',
                'verbose_name_plural': 'Curriculum Units',
                'ordering': ['class_session', 'subject', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='TimetableException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('exception_type', models.CharField(choices=[('holiday', 'Public Holiday'), ('closure', 'School Closure'), ('exam', 'Examination Period'), ('event', 'School Event'), ('emergency', 'Emergency Closure')], default='holiday', max_length=20)),
                ('affects_all_classes', models.BooleanField(default=True, help_text='If False, only the class_sessions listed below are affected.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_sessions', models.ManyToManyField(blank=True, help_text='Relevant only when affects_all_classes=False.', related_name='timetable_exceptions', to='academics.classsession')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timetable Exception',
                'verbose_name_plural': 'Timetable Exceptions',
                'ordering': ['date_from'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('effective_from', models.DateField(help_text='Date from which this slot takes effect. Usually the term start date.')),
                ('effective_until', models.DateField(blank=True, help_text='Date until which this slot is valid. Null = valid until term ends.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_session', models.ForeignKey(help_text='The Grade+Term academic container this slot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.classsession')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots_created', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='timetable.room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='timetable.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timetable Slot',
                'verbose_name_plural': 'Timetable Slots',
                'ordering': ['day_of_week', 'start_time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('class_session', 'day_of_week', 'start_time', 'effective_from'), name='unique_class_timeslot'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('room__isnull', False)), fields=('room', 'day_of_week', 'start_time', 'effective_from'), name='unique_room_timeslot'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('teacher', 'day_of_week', 'start_time', 'effective_from'), name='unique_teacher_timeslot')],
            },
        ),
    ]
