# Generated by Django 6.0.2 on 2026-03-03 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("student_settings", "0008_enrollment_reporting_reason_enrollment_stay_status"),
        ("timetable", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lock_level",
                    models.CharField(
                        choices=[
                            ("draft", "Draft - Fully Editable"),
                            ("review", "Under Review - Admin Only"),
                            ("locked", "Locked - No Edits"),
                            ("archived", "Archived - Historical"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("unlock_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_session",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_lock",
                        to="academics.classsession",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetables_locked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_locks",
                        to="student_settings.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Lock",
                "verbose_name_plural": "Timetable Locks",
            },
        ),
        migrations.CreateModel(
            name="TeacherAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "availability_type",
                    models.CharField(
                        choices=[
                            ("unavailable", "Not Available"),
                            ("preferred", "Preferred"),
                            ("avoid", "Avoid if Possible"),
                        ],
                        default="unavailable",
                        max_length=20,
                    ),
                ),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("once", "One-time"),
                            ("weekly", "Weekly Recurring"),
                            ("term", "Entire Term"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                        ],
                        null=True,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("all_day", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_availabilities",
                        to="student_settings.academicyear",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="availability_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Availability",
                "verbose_name_plural": "Teacher Availabilities",
                "ordering": ["teacher", "day_of_week", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "day_of_week"],
                        name="timetable_t_teacher_7c58bd_idx",
                    ),
                    models.Index(
                        fields=["teacher", "is_active"],
                        name="timetable_t_teacher_258196_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TimePeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name, e.g., 'Period 1', 'Morning Break'",
                        max_length=50,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Short code for UI, e.g., 'P1', 'BRK'", max_length=10
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("lesson", "Lesson Period"),
                            ("break", "Break"),
                            ("assembly", "Assembly"),
                            ("lunch", "Lunch"),
                            ("activity", "Extra-curricular"),
                        ],
                        default="lesson",
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="Sort order within a day (1=first period)"
                    ),
                ),
                (
                    "is_schedulable",
                    models.BooleanField(
                        default=True,
                        help_text="Can lessons be scheduled in this period?",
                    ),
                ),
                (
                    "applies_to_days",
                    models.CharField(
                        default="0,1,2,3,4,5",
                        help_text="Comma-separated day indices (0=Mon, 5=Sat). Empty = all days.",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        help_text="If null, applies to all academic years",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_periods",
                        to="student_settings.academicyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Period",
                "verbose_name_plural": "Time Periods",
                "ordering": ["order", "start_time"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("academic_year", "order"),
                        name="unique_period_order_per_year",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TimetableVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "name",
                    models.CharField(
                        help_text="Version name, e.g., 'Initial Draft', 'After PE adjustment'",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "slot_data",
                    models.JSONField(
                        help_text="JSON snapshot of all TimetableSlots for this class_session"
                    ),
                ),
                ("total_slots", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("was_restored", models.BooleanField(default=False)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "class_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_versions",
                        to="academics.classsession",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_versions_restored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Version",
                "verbose_name_plural": "Timetable Versions",
                "ordering": ["-version_number"],
                "unique_together": {("class_session", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="WorkAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lessons_per_week",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Number of lessons this teacher should teach this subject to this class weekly",
                    ),
                ),
                (
                    "required_room_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("classroom", "Classroom"),
                            ("lab", "Laboratory"),
                            ("hall", "Assembly Hall / Multipurpose"),
                            ("library", "Library"),
                            ("field", "Sports Field / Outdoor"),
                            ("online", "Online / Virtual"),
                        ],
                        help_text="Required room type (hard constraint). Empty = any room.",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="1=highest priority (scheduled first), 10=lowest",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_allocations",
                        to="academics.classsession",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_allocations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preferred_room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preferred room for this allocation (soft constraint)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_allocations",
                        to="timetable.room",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_allocations",
                        to="timetable.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Allocation",
                "verbose_name_plural": "Work Allocations",
                "ordering": ["priority", "class_session", "subject"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "class_session"],
                        name="timetable_w_teacher_f3391e_idx",
                    ),
                    models.Index(
                        fields=["subject", "class_session"],
                        name="timetable_w_subject_5e375b_idx",
                    ),
                    models.Index(
                        fields=["class_session", "is_active"],
                        name="timetable_w_class_s_6f3717_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("teacher", "subject", "class_session"),
                        name="unique_work_allocation",
                    )
                ],
            },
        ),
    ]
