# Generated by Django 6.0.2 on 2026-03-05 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_settings", "0009_learningarea"),
        ("timetable", "0002_timetablelock_teacheravailability_timeperiod_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="learning_area",
            field=models.ForeignKey(
                blank=True,
                help_text="Learning area / subject category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to="student_settings.learningarea",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="subject_type",
            field=models.CharField(
                choices=[
                    ("compulsory", "Compulsory"),
                    ("optional", "Optional"),
                    ("elective", "Elective"),
                ],
                default="compulsory",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="weekly_lessons",
            field=models.PositiveSmallIntegerField(
                default=5, help_text="Default lessons per week"
            ),
        ),
    ]
