# Generated by Django 6.0.3 on 2026-04-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0003_subject_learning_area_subject_subject_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timetablelock",
            options={},
        ),
        migrations.RenameIndex(
            model_name="teacheravailability",
            new_name="teacher_ava_teacher_1bd618_idx",
            old_name="timetable_t_teacher_7c58bd_idx",
        ),
        migrations.RenameIndex(
            model_name="teacheravailability",
            new_name="teacher_ava_teacher_acef94_idx",
            old_name="timetable_t_teacher_258196_idx",
        ),
        migrations.RenameIndex(
            model_name="workallocation",
            new_name="work_alloca_teacher_7370e4_idx",
            old_name="timetable_w_teacher_f3391e_idx",
        ),
        migrations.RenameIndex(
            model_name="workallocation",
            new_name="work_alloca_subject_73c01f_idx",
            old_name="timetable_w_subject_5e375b_idx",
        ),
        migrations.RenameIndex(
            model_name="workallocation",
            new_name="work_alloca_class_s_063091_idx",
            old_name="timetable_w_class_s_6f3717_idx",
        ),
        migrations.AlterModelTable(
            name="curriculumunit",
            table="curriculum_units",
        ),
        migrations.AlterModelTable(
            name="room",
            table="rooms",
        ),
        migrations.AlterModelTable(
            name="subject",
            table="subjects",
        ),
        migrations.AlterModelTable(
            name="teacheravailability",
            table="teacher_availabilities",
        ),
        migrations.AlterModelTable(
            name="timeperiod",
            table="time_periods",
        ),
        migrations.AlterModelTable(
            name="timetableexception",
            table="timetable_exceptions",
        ),
        migrations.AlterModelTable(
            name="timetablelock",
            table="timetable_locks",
        ),
        migrations.AlterModelTable(
            name="timetableslot",
            table="timetable_slots",
        ),
        migrations.AlterModelTable(
            name="timetableversion",
            table="timetable_versions",
        ),
        migrations.AlterModelTable(
            name="workallocation",
            table="work_allocations",
        ),
    ]
