# Generated by Django 6.0.3 on 2026-06-18 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_settings", "0015_admissionworkflowconfig"),
        ("timetable", "0004_alter_timetablelock_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeSubjectMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_core",
                    models.BooleanField(
                        default=True,
                        help_text="Is this subject compulsory for this grade?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_mappings",
                        to="student_settings.gradestructure",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_mappings",
                        to="timetable.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Subject Mapping",
                "verbose_name_plural": "Grade Subject Mappings",
                "db_table": "grade_subject_mappings",
                "unique_together": {("grade", "subject")},
            },
        ),
    ]
