# Generated by Django 6.0.3 on 2026-07-27 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='finance.account'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budgets.budget'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetline',
            unique_together={('budget', 'account')},
        ),
    ]
