# Generated by Django 6.0.2 on 2026-02-27 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('missed', 'Missed'), ('cancelled', 'Cancelled'), ('holiday', 'Holiday / School Closed')], default='pending', max_length=20)),
                ('scheduled_start_time', models.TimeField()),
                ('scheduled_end_time', models.TimeField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(default='scheduler', max_length=50)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_planned_lessons', to=settings.AUTH_USER_MODEL)),
                ('class_session', models.ForeignKey(help_text='The Grade+Term academic container — NOT an operational session.', on_delete=django.db.models.deletion.CASCADE, related_name='planned_lessons', to='academics.classsession')),
                ('expected_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planned Lesson',
                'verbose_name_plural': 'Planned Lessons',
                'ordering': ['date', 'scheduled_start_time'],
            },
        ),
    ]
