# Generated by Django 6.0.2 on 2026-02-27 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduled_lessons', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedlesson',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_lessons', to='timetable.room'),
        ),
        migrations.AddField(
            model_name='plannedlesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_lessons', to='timetable.subject'),
        ),
        migrations.AddField(
            model_name='plannedlesson',
            name='timetable_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_lessons', to='timetable.timetableslot'),
        ),
        migrations.AddIndex(
            model_name='plannedlesson',
            index=models.Index(fields=['date', 'status'], name='scheduled_l_date_b67e54_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedlesson',
            index=models.Index(fields=['class_session', 'date'], name='scheduled_l_class_s_0c7e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedlesson',
            index=models.Index(fields=['expected_teacher', 'date'], name='scheduled_l_expecte_280089_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedlesson',
            index=models.Index(fields=['subject', 'date'], name='scheduled_l_subject_c8364b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plannedlesson',
            unique_together={('timetable_slot', 'date')},
        ),
    ]
