# Generated by Django 6.0.3 on 2026-07-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_percent', models.PositiveSmallIntegerField(default=100, help_text='Percentage of this unit covered in this session (0–100).')),
                ('teacher_notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curriculum Coverage',
                'verbose_name_plural': 'Curriculum Coverage Records',
            },
        ),
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_start_time', models.DateTimeField(help_text='Actual datetime the lesson started.')),
                ('actual_end_time', models.DateTimeField(blank=True, help_text='Actual datetime the lesson ended. Null while ongoing.', null=True)),
                ('date', models.DateField(db_index=True)),
                ('topic_taught', models.CharField(blank=True, max_length=255)),
                ('lesson_notes', models.TextField(blank=True)),
                ('homework_given', models.TextField(blank=True)),
                ('delivery_mode', models.CharField(choices=[('physical', 'Physical Classroom'), ('online', 'Online / Virtual'), ('hybrid', 'Hybrid')], default='physical', max_length=20)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='ongoing', max_length=20)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lesson Session',
                'verbose_name_plural': 'Lesson Sessions',
                'ordering': ['-date', 'actual_start_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused Absent')], default='absent', max_length=20)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('minutes_late', models.PositiveSmallIntegerField(default=0, help_text='How many minutes late the student arrived. Relevant when status=late.')),
                ('is_locked', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Session Attendance',
                'verbose_name_plural': 'Session Attendance Records',
            },
        ),
        migrations.CreateModel(
            name='TeacherSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('sick_leave', 'Teacher Sick Leave'), ('emergency', 'Personal Emergency'), ('training', 'Training / Workshop'), ('travel', 'Official Travel'), ('no_show', 'Teacher No-Show'), ('other', 'Other')], max_length=30)),
                ('reason_notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Teacher Substitution',
                'verbose_name_plural': 'Teacher Substitutions',
                'ordering': ['-requested_at'],
            },
        ),
    ]
