# Generated by Django 6.0.2 on 2026-02-27 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0010_activity'),
        ('lesson_sessions', '0001_initial'),
        ('scheduled_lessons', '0002_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumcoverage',
            name='curriculum_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_records', to='timetable.curriculumunit'),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='actual_teacher',
            field=models.ForeignKey(help_text='The teacher who actually conducted this lesson.', on_delete=django.db.models.deletion.PROTECT, related_name='conducted_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='class_session',
            field=models.ForeignKey(help_text='The Grade+Term period this lesson belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='lesson_sessions', to='academics.classsession'),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='curriculum_unit',
            field=models.ForeignKey(blank=True, help_text='The curriculum unit/topic covered in this session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_sessions', to='timetable.curriculumunit'),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='planned_lesson',
            field=models.OneToOneField(blank=True, help_text='The planned lesson this execution corresponds to. Null for ad-hoc sessions.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_session', to='scheduled_lessons.plannedlesson'),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_sessions', to='timetable.room'),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_started', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_sessions', to='timetable.subject'),
        ),
        migrations.AddField(
            model_name='curriculumcoverage',
            name='lesson_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_records', to='lesson_sessions.lessonsession'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='lesson_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='lesson_sessions.lessonsession'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_markings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attendances', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='teachersubstitution',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitutions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachersubstitution',
            name='original_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons_substituted_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachersubstitution',
            name='planned_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='scheduled_lessons.plannedlesson'),
        ),
        migrations.AddField(
            model_name='teachersubstitution',
            name='substitute_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitute_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lessonsession',
            index=models.Index(fields=['date', 'status'], name='lesson_sess_date_f02984_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonsession',
            index=models.Index(fields=['class_session', 'date'], name='lesson_sess_class_s_d8b8af_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonsession',
            index=models.Index(fields=['actual_teacher', 'date'], name='lesson_sess_actual__1ce9ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumcoverage',
            unique_together={('curriculum_unit', 'lesson_session')},
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['student', 'status'], name='lesson_sess_student_01c97c_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['lesson_session', 'status'], name='lesson_sess_lesson__32cea9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('lesson_session', 'student')},
        ),
    ]
