from rest_framework import viewsets, filters, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from django_filters.rest_framework import DjangoFilterBackend
from django.utils import timezone

from .models import PlannedLesson
from .serializers import PlannedLessonSerializer


class PlannedLessonViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Planned lessons are generated by the scheduler.
    The API is read-only except for admin cancel/regenerate actions.
    """
    serializer_class = PlannedLessonSerializer
    permission_classes = [IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.OrderingFilter]
    filterset_fields = ['date', 'status', 'class_session', 'subject', 'expected_teacher']
    ordering_fields = ['date', 'scheduled_start_time']

    def get_queryset(self):
        return PlannedLesson.objects.select_related(
            'timetable_slot', 'class_session', 'subject', 'room', 'expected_teacher'
        ).prefetch_related('lesson_session')

    @action(detail=False, methods=['get'], url_path='today')
    def today(self, request):
        """
        Returns all planned lessons for today.
        Optionally filter by class_session or teacher.
        """
        today = timezone.localdate()
        qs = self.get_queryset().filter(date=today).order_by('scheduled_start_time')

        class_session_id = request.query_params.get('class_session')
        teacher_id = request.query_params.get('teacher')

        if class_session_id:
            qs = qs.filter(class_session_id=class_session_id)
        if teacher_id:
            qs = qs.filter(expected_teacher_id=teacher_id)

        return Response(PlannedLessonSerializer(qs, many=True).data)

    @action(detail=True, methods=['post'], url_path='cancel')
    def cancel(self, request, pk=None):
        lesson = self.get_object()
        if lesson.status not in ('pending',):
            return Response(
                {'error': f"Cannot cancel a lesson with status '{lesson.status}'."},
                status=400
            )
        reason = request.data.get('reason', '')
        lesson.status = 'cancelled'
        lesson.cancellation_reason = reason
        lesson.cancelled_by = request.user
        lesson.save(update_fields=['status', 'cancellation_reason', 'cancelled_by'])
        return Response({'status': 'cancelled', 'id': lesson.pk})

    @action(detail=False, methods=['post'], url_path='regenerate')
    def regenerate(self, request):
        """
        Admin-triggered regeneration for a class_session and date range.
        Payload: { class_session_id, from_date, days }
        """
        class_session_id = request.data.get('class_session_id')
        from_date = request.data.get('from_date', timezone.localdate().isoformat())
        days = int(request.data.get('days', 30))

        from django.core.management import call_command
        kwargs = {'from_date': from_date, 'days': days, 'force': True}
        if class_session_id:
            kwargs['class_session'] = int(class_session_id)
        call_command('generate_planned_lessons', **kwargs)

        return Response({
            'regenerated': True,
            'from_date': from_date,
            'days': days,
            'class_session_id': class_session_id,
        })

    @action(detail=False, methods=['get'], url_path='summary')
    def summary(self, request):
        """
        Planned vs actual summary for a class_session in a date range.
        Query: ?class_session=<id>&from_date=YYYY-MM-DD&to_date=YYYY-MM-DD
        """
        from datetime import date
        class_session_id = request.query_params.get('class_session')
        from_date = request.query_params.get('from_date', date.today().isoformat())
        to_date   = request.query_params.get('to_date', date.today().isoformat())

        qs = PlannedLesson.objects.filter(date__range=(from_date, to_date))
        if class_session_id:
            qs = qs.filter(class_session_id=class_session_id)

        total     = qs.count()
        executed  = qs.filter(status='executed').count()
        missed    = qs.filter(status='missed').count()
        cancelled = qs.filter(status='cancelled').count()
        pending   = qs.filter(status='pending').count()
        holiday   = qs.filter(status='holiday').count()

        return Response({
            'total_planned': total,
            'executed':      executed,
            'missed':        missed,
            'cancelled':     cancelled,
            'pending':       pending,
            'holiday':       holiday,
            'execution_rate': round((executed / max(total, 1)) * 100, 1),
        })
