# Generated by Django 6.0.1 on 2026-01-31 00:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_remove_student_level_remove_student_program_and_more'),
        ('student_settings', '0006_intake_entry_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Auto-generated name, e.g., 'Grade 1 - Term 1 2026'", max_length=150)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='scheduled', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_sessions', to='student_settings.academicyear')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_sessions', to='student_settings.curriculum')),
                ('curriculum_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_sessions', to='student_settings.curriculumlevel')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_sessions', to='student_settings.gradestructure')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_sessions', to='student_settings.term')),
            ],
            options={
                'verbose_name': 'Class Session',
                'verbose_name_plural': 'Class Sessions',
                'ordering': ['academic_year__start_date', 'term__start_date', 'grade__level_order'],
                'unique_together': {('grade', 'term', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentSessionEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('transferred_out', 'Transferred Out'), ('dropped', 'Dropped'), ('expelled', 'Expelled')], default='active', max_length=20)),
                ('progression_status', models.CharField(choices=[('promoted', 'Promoted'), ('retained', 'Retained/Repeated'), ('graduated', 'Graduated'), ('discontinued', 'Discontinued'), ('pending', 'Pending Decision')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text="Is this the student's CURRENT active session?")),
                ('reporting_date', models.DateField(default=django.utils.timezone.now)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intake', models.ForeignKey(help_text='The intake cohort this student belongs to (immutable usually)', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='student_settings.intake')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='academics.classsession')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_students', to='student_settings.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_enrollments', to='accounts.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'is_active'], name='academics_s_student_ae64b0_idx'), models.Index(fields=['session', 'status'], name='academics_s_session_8c3098_idx')],
                'unique_together': {('student', 'session')},
            },
        ),
    ]
