# Generated by Django 6.0.3 on 2026-07-27 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('course', '0001_initial'),
        ('student_management', '0001_initial'),
        ('student_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_sessions', to='student_settings.academicyear'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The university/modular course section for this session', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_sessions', to='course.course'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_sessions', to='student_settings.curriculum'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='curriculum_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_sessions', to='student_settings.curriculumlevel'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_sessions', to='student_settings.gradestructure'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_sessions', to='student_settings.term'),
        ),
        migrations.AddField(
            model_name='studentsessionenrollment',
            name='intake',
            field=models.ForeignKey(help_text='The intake cohort this student belongs to (immutable usually)', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='student_settings.intake'),
        ),
        migrations.AddField(
            model_name='studentsessionenrollment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='academics.classsession'),
        ),
        migrations.AddField(
            model_name='studentsessionenrollment',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_students', to='student_settings.stream'),
        ),
        migrations.AddField(
            model_name='studentsessionenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_enrollments', to='student_management.student'),
        ),
        migrations.AlterUniqueTogether(
            name='classsession',
            unique_together={('grade', 'term', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='studentsessionenrollment',
            index=models.Index(fields=['student', 'is_active'], name='student_ses_student_1bba03_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsessionenrollment',
            index=models.Index(fields=['session', 'status'], name='student_ses_session_a4f99d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsessionenrollment',
            unique_together={('student', 'session')},
        ),
    ]
