# Generated by Django 6.0.3 on 2026-04-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="studentsessionenrollment",
            new_name="student_ses_student_1bba03_idx",
            old_name="academics_s_student_ae64b0_idx",
        ),
        migrations.RenameIndex(
            model_name="studentsessionenrollment",
            new_name="student_ses_session_a4f99d_idx",
            old_name="academics_s_session_8c3098_idx",
        ),
        migrations.AlterModelTable(
            name="classsession",
            table="class_sessions",
        ),
        migrations.AlterModelTable(
            name="studentsessionenrollment",
            table="student_session_enrollments",
        ),
    ]
