# Generated by Django 6.0.3 on 2026-05-21 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0002_rename_academics_s_student_ae64b0_idx_student_ses_student_1bba03_idx_and_more",
        ),
        ("course", "0005_remove_course_level_remove_course_semester_and_more"),
        ("student_settings", "0014_gradestructure_credits_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsession",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="The university/modular course section for this session",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="academic_sessions",
                to="course.course",
            ),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="academic_sessions",
                to="student_settings.gradestructure",
            ),
        ),
    ]
