# Generated by Django 6.0.3 on 2026-07-27 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='student_management.student'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendance',
            unique_together={('student', 'date')},
        ),
    ]
