# Generated by Django 6.0.3 on 2026-07-27 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_initial'),
        ('student_management', '0001_initial'),
        ('student_settings', '0001_initial'),
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applying_for_curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='student_settings.curriculum'),
        ),
        migrations.AddField(
            model_name='application',
            name='applying_for_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='student_settings.gradestructure'),
        ),
        migrations.AddField(
            model_name='application',
            name='applying_for_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='student_settings.curriculumlevel'),
        ),
        migrations.AddField(
            model_name='application',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Campus the applicant is applying to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campus_applications', to='workforce.campus'),
        ),
        migrations.AddField(
            model_name='application',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='student_settings.intake'),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admission',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='admission', to='student_management.application'),
        ),
        migrations.AddField(
            model_name='applicationfeepayment',
            name='application',
            field=models.OneToOneField(help_text='The application this fee is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='fee_payment', to='student_management.application'),
        ),
        migrations.AddField(
            model_name='applicationfeepayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationfeepayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payments_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationfeepayment',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completion',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_settings.curriculum'),
        ),
        migrations.AddField(
            model_name='completion',
            name='curriculum_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student_settings.curriculumlevel'),
        ),
        migrations.AddField(
            model_name='completion',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmenthead',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.program'),
        ),
        migrations.AddField(
            model_name='departmenthead',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Staff member responsible for following up', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='workforce.campus'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='converted_application',
            field=models.OneToOneField(blank=True, help_text='The Application created from this enquiry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_source', to='student_management.application'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='student_settings.curriculum'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Grade/class level they are enquiring about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='student_settings.gradestructure'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='intake',
            field=models.ForeignKey(blank=True, help_text='Which intake are they interested in?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='student_settings.intake'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='application',
            field=models.OneToOneField(help_text='The application being interviewed', on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='student_management.application'),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='Staff who recorded the interview outcome', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_interview_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='interviewer',
            field=models.ForeignKey(blank=True, help_text='Primary interviewer (staff member)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='panel_members',
            field=models.ManyToManyField(blank=True, help_text='Additional panel members', related_name='interview_panel_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_interview_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportingrecord',
            name='application',
            field=models.OneToOneField(help_text='The application this reporting record is for', on_delete=django.db.models.deletion.CASCADE, related_name='reporting_record', to='student_management.application'),
        ),
        migrations.AddField(
            model_name='reportingrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportingrecord',
            name='received_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who received the student on reporting day', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_records_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportingrecord',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Primary campus this student belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='workforce.campus'),
        ),
        migrations.AddField(
            model_name='student',
            name='intake',
            field=models.ForeignKey(blank=True, help_text='The intake cohort this student belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='student_settings.intake'),
        ),
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='student_management.student'),
        ),
        migrations.AddField(
            model_name='completion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='student_management.student'),
        ),
        migrations.AddField(
            model_name='admission',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='admission_record', to='student_management.student'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='student_settings.academicyear'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='student_settings.curriculum'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='curriculum_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='student_settings.curriculumlevel'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='student_settings.gradestructure'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='student_settings.intake'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='previous_placement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_placement', to='student_management.studentplacement'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='student_settings.stream'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='student_management.student'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='student_settings.term'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studentplacement',
            index=models.Index(fields=['student', 'session_status'], name='student_pla_student_de839e_idx'),
        ),
    ]
