# Generated by Django 6.0.1 on 2026-01-27 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_alter_application_applying_for_level'),
        ('student_settings', '0005_gradestructure_curriculum_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='curriculum_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_sessions', to='student_settings.curriculumlevel'),
        ),
    ]
