# Generated by Django 6.0.1 on 2026-01-31 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_student_status'),
        ('student_management', '0003_alter_classsession_curriculum_level'),
        ('student_settings', '0006_intake_entry_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('session_type', models.CharField(choices=[('admission', 'Admission'), ('reporting', 'Reporting'), ('promotion', 'Promotion'), ('repeat', 'Repeat'), ('transfer', 'Transfer In')], default='reporting', max_length=20)),
                ('session_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('transferred', 'Transferred Out'), ('dropped', 'Dropped')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Student Placement',
                'verbose_name_plural': 'Student Placements',
                'ordering': ['-academic_year__start_date', '-term__start_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='classsession',
            name='student_man_student_caeba5_idx',
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='student_settings.academicyear'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='student_settings.curriculum'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='curriculum_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='student_settings.curriculumlevel'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='student_settings.gradestructure'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='student_settings.intake'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='previous_placement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_placement', to='student_management.studentplacement'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='student_settings.stream'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='student_settings.term'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='curriculum_level',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='intake',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='previous_session',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='student',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='term',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='updated_by',
        ),
        migrations.AddIndex(
            model_name='studentplacement',
            index=models.Index(fields=['student', 'session_status'], name='student_man_student_d04e4a_idx'),
        ),
        migrations.DeleteModel(
            name='ClassSession',
        ),
    ]
