# Generated by Django 6.0.2 on 2026-03-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management", "0004_studentplacement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="allergies",
            field=models.TextField(blank=True, help_text="Known allergies", null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="assessment_score",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="birth_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="applications/documents/"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="birth_certificate_number",
            field=models.CharField(
                blank=True,
                help_text="Birth certificate number",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="county",
            field=models.CharField(
                blank=True, help_text="County of residence", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="doctor_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="doctor_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="emergency_contact_relationship",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="guardian2_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="guardian2_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="guardian2_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="guardian2_relationship",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="guardian_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="guardian_id_number",
            field=models.CharField(
                blank=True,
                help_text="National ID or Passport",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="guardian_occupation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="guardian_relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("father", "Father"),
                    ("mother", "Mother"),
                    ("guardian", "Guardian"),
                    ("uncle", "Uncle"),
                    ("aunt", "Aunt"),
                    ("grandparent", "Grandparent"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="health_insurance",
            field=models.CharField(
                blank=True,
                help_text="NHIF or private insurance",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="home_address",
            field=models.TextField(
                blank=True, help_text="Physical home address", null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="is_transfer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="application",
            name="medical_conditions",
            field=models.TextField(
                blank=True, help_text="Any known medical conditions", null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="medical_report",
            field=models.FileField(
                blank=True, null=True, upload_to="applications/documents/"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="middle_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="nationality",
            field=models.CharField(
                blank=True, default="Kenyan", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="passport_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="applications/photos/"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="previous_class",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="previous_report_card",
            field=models.FileField(
                blank=True, null=True, upload_to="applications/documents/"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="previous_school_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="previous_school_contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="previous_school_leaving_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="previous_school_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="referral_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("walk_in", "Walk-in"),
                    ("online", "Online"),
                    ("referral", "Referral"),
                    ("advertisement", "Advertisement"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="religion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("christian", "Christian"),
                    ("muslim", "Muslim"),
                    ("hindu", "Hindu"),
                    ("traditional", "African Traditional"),
                    ("other", "Other"),
                    ("none", "None"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="special_needs",
            field=models.TextField(
                blank=True,
                help_text="Special educational needs or requirements",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="sub_county",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="transfer_letter",
            field=models.FileField(
                blank=True, null=True, upload_to="applications/documents/"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="transfer_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
