# Generated by Django 6.0.3 on 2026-04-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_management",
            "0005_application_allergies_application_assessment_score_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admission",
            options={"ordering": ["-admission_date"]},
        ),
        migrations.RenameIndex(
            model_name="studentplacement",
            new_name="student_pla_student_de839e_idx",
            old_name="student_man_student_d04e4a_idx",
        ),
        migrations.AlterModelTable(
            name="admission",
            table="student_admissions",
        ),
        migrations.AlterModelTable(
            name="application",
            table="student_applications",
        ),
        migrations.AlterModelTable(
            name="completion",
            table="student_completions",
        ),
        migrations.AlterModelTable(
            name="studentplacement",
            table="student_placements",
        ),
    ]
