# Generated by Django 6.0.3 on 2026-04-09 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0006_alter_admission_options_and_more'),
        ('workforce', '0008_add_institution_to_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Campus the student was admitted to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='workforce.campus'),
        ),
        migrations.AddField(
            model_name='application',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Campus the applicant is applying to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='workforce.campus'),
        ),
    ]
