# Generated by Django 6.0.3 on 2026-04-10 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management", "0007_admission_campus_application_campus"),
        ("workforce", "0009_employee_campus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                help_text="Campus the student was admitted to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campus_admissions",
                to="workforce.campus",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                help_text="Campus the applicant is applying to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campus_applications",
                to="workforce.campus",
            ),
        ),
    ]
