# Generated by Django 6.0.3 on 2026-05-23 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management", "0008_alter_admission_campus_alter_application_campus"),
        ("student_settings", "0015_admissionworkflowconfig"),
        ("workforce", "0017_attendancepolicy_allow_biometric_clock_in_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("fee_pending", "Registration Fee Pending"),
                    ("fee_paid", "Registration Fee Paid"),
                    ("interview", "Interview Scheduled"),
                    ("interviewed", "Interview Completed"),
                    ("reporting", "Reporting Scheduled"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("waitlist", "Waitlisted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ApplicationFeePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount charged (copied from AdmissionWorkflowConfig at creation time)",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("paid", "Paid"),
                            ("waived", "Waived"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("mpesa", "M-Pesa"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="M-Pesa code, bank slip number, cheque number, etc.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        help_text="Internal receipt number issued by the school",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "waiver_reason",
                    models.TextField(
                        blank=True,
                        help_text="Required if status=waived — explain why the fee was waived",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        help_text="The application this fee is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_payment",
                        to="student_management.application",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who recorded this payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fee_payments_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Fee Payment",
                "db_table": "application_fee_payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "full_name",
                    models.CharField(
                        help_text="Name of the parent or enquiring party",
                        max_length=200,
                    ),
                ),
                (
                    "child_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the prospective student",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Free-text message from the enquiring party",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("walk_in", "Walk-in"),
                            ("phone", "Phone Call"),
                            ("email", "Email"),
                            ("website", "Website Form"),
                            ("referral", "Referral"),
                            ("social_media", "Social Media"),
                            ("open_day", "Open Day"),
                            ("other", "Other"),
                        ],
                        default="walk_in",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("converted", "Converted to Application"),
                            ("dropped", "Dropped"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, help_text="Scheduled follow-up date", null=True
                    ),
                ),
                ("follow_up_notes", models.TextField(blank=True, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member responsible for following up",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_enquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries",
                        to="workforce.campus",
                    ),
                ),
                (
                    "converted_application",
                    models.OneToOneField(
                        blank=True,
                        help_text="The Application created from this enquiry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiry_source",
                        to="student_management.application",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries",
                        to="student_settings.curriculum",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        help_text="Grade/class level they are enquiring about",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries",
                        to="student_settings.gradestructure",
                    ),
                ),
                (
                    "intake",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which intake are they interested in?",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries",
                        to="student_settings.intake",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Enquiry",
                "verbose_name_plural": "Enquiries",
                "db_table": "student_enquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scheduled_date",
                    models.DateTimeField(help_text="Date and time of the interview"),
                ),
                (
                    "venue",
                    models.CharField(
                        blank=True,
                        help_text="Room name, building, or online link",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=30, help_text="Expected duration in minutes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("pass", "Pass"),
                            ("conditional", "Conditional Pass"),
                            ("fail", "Fail"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Numeric score if interview uses scoring rubric",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum possible score",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interviewer notes — visible to admin only",
                        null=True,
                    ),
                ),
                (
                    "feedback_to_applicant",
                    models.TextField(
                        blank=True,
                        help_text="Optional feedback communicated to the applicant/guardian",
                        null=True,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        help_text="The application being interviewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview",
                        to="student_management.application",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff who recorded the interview outcome",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interviews_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_interview_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary interviewer (staff member)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "panel_members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Additional panel members",
                        related_name="interview_panel_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_interview_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interview Schedule",
                "db_table": "application_interviews",
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="ReportingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expected_date",
                    models.DateField(
                        help_text="Date the student is expected to report"
                    ),
                ),
                (
                    "actual_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the student actually reported",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("expected", "Expected"),
                            ("reported", "Reported"),
                            ("absent", "Did Not Report"),
                            ("deferred", "Deferred to Later Date"),
                        ],
                        default="expected",
                        max_length=20,
                    ),
                ),
                (
                    "documents_received",
                    models.BooleanField(
                        default=False,
                        help_text="True when all required documents have been received",
                    ),
                ),
                (
                    "document_status",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Per-document submission status. Key = document name, Value = "received" | "missing" | "partial". e.g. {"Birth Certificate": "received", "Passport Photo": "missing"}',
                    ),
                ),
                (
                    "missing_documents",
                    models.TextField(
                        blank=True,
                        help_text="Free-text list of any documents still outstanding",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        help_text="The application this reporting record is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reporting_record",
                        to="student_management.application",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who received the student on reporting day",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reporting_records_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporting Record",
                "db_table": "application_reporting_records",
                "ordering": ["expected_date"],
            },
        ),
    ]
