# Generated by Django 6.0.3 on 2026-07-27 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('examinations', '0001_initial'),
        ('student_management', '0001_initial'),
        ('student_settings', '0001_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttype',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_types', to='student_settings.curriculum'),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='curriculum_level',
            field=models.ForeignKey(blank=True, help_text='If set, this type applies only to this level', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_types', to='student_settings.curriculumlevel'),
        ),
        migrations.AddField(
            model_name='examination',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='examinations.assessmenttype'),
        ),
        migrations.AddField(
            model_name='examination',
            name='class_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='academics.classsession'),
        ),
        migrations.AddField(
            model_name='examination',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examination',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examination',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='timetable.subject'),
        ),
        migrations.AddField(
            model_name='examination',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradinglevel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradingscale',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradingscale',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_scales', to='student_settings.curriculum'),
        ),
        migrations.AddField(
            model_name='gradingscale',
            name='curriculum_level',
            field=models.ForeignKey(blank=True, help_text='If set, this scale applies only to this level within the curriculum', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grading_scales', to='student_settings.curriculumlevel'),
        ),
        migrations.AddField(
            model_name='gradinglevel',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='examinations.gradingscale'),
        ),
        migrations.AddField(
            model_name='examination',
            name='grading_scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='examinations.gradingscale'),
        ),
        migrations.AddField(
            model_name='reportcardtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcardtemplate',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_templates', to='student_settings.curriculum'),
        ),
        migrations.AddField(
            model_name='reportcardtemplate',
            name='curriculum_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_templates', to='student_settings.curriculumlevel'),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='examinations.examination'),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_marks', to='student_settings.stream'),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_marks', to='student_management.student'),
        ),
        migrations.AddField(
            model_name='termresult',
            name='class_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_results', to='academics.classsession'),
        ),
        migrations.AddField(
            model_name='termresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termresult',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_settings.stream'),
        ),
        migrations.AddField(
            model_name='termresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_results', to='student_management.student'),
        ),
        migrations.AddField(
            model_name='termsubjectresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termsubjectresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_subject_results', to='timetable.subject'),
        ),
        migrations.AddField(
            model_name='termsubjectresult',
            name='term_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='examinations.termresult'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmenttype',
            unique_together={('curriculum', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='gradinglevel',
            unique_together={('scale', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together={('examination', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='termresult',
            unique_together={('student', 'class_session')},
        ),
        migrations.AlterUniqueTogether(
            name='termsubjectresult',
            unique_together={('term_result', 'subject')},
        ),
    ]
